// Code generated by re2c 3.1 on Mon Jun  1 16:13:41 2026, DO NOT EDIT.
//line "_normalize.re.go":1
//go:generate re2go -W -Werror -8 -o normalize.go _normalize.re.go

package main

import (
	"log"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/rivo/uniseg"
)

// Dummy variables to prevent IDE formatters from stripping required imports.
var (
	_ = utf8.DecodeRuneInString
	_ = unicode.IsLetter
	_ = log.Fatalf
)

const (
	Pnul = iota
	Pa
	Pā
	Pi
	Pī
	Pu
	Pū
	Pṛ
	Pṝ
	Pḷ
	Pḹ
	Pe
	Pai
	Po
	Pau
	Pṃ
	Pḥ
	Pk
	Pkh
	Pg
	Pgh
	Pṅ
	Pc
	Pch
	Pj
	Pjh
	Pñ
	Pṭ
	Pṭh
	Pḍ
	Pḍh
	Pṇ
	Pt
	Pth
	Pd
	Pdh
	Pn
	Pp
	Pph
	Pb
	Pbh
	Pm
	Py
	Pr
	Pl
	Pv
	Pś
	Pṣ
	Ps
	Ph
	Pschwa
	Plongschwa
	Pother
)

var phonemeLookup = []string{
	"!",
	"a", "ā", "i", "ī", "u", "ū",
	"ṛ", "ṝ", "ḷ", "ḹ",
	"e", "ai", "o", "au",
	"ṃ", "ḥ",
	"k", "kh", "g", "gh", "ṅ",
	"c", "ch", "j", "jh", "ñ",
	"ṭ", "ṭh", "ḍ", "ḍh", "ṇ",
	"t", "th", "d", "dh", "n",
	"p", "ph", "b", "bh", "m",
	"y", "r", "l", "v",
	"ś", "ṣ", "s", "h",
	"ə", "ə̄",
	"?",
}

// peekByte safely reads a byte from a string to prevent out-of-bounds panics in re2c.
// It returns 0 when the cursor reaches or exceeds the string length.
func peekByte(s string, i int) byte {
	if i < len(s) {
		return s[i]
	}
	return 0
}

func makePrintable(s string) string {
	var buf strings.Builder
	for i := 0; i < len(s); i++ {
		c := int(s[i])
		buf.WriteString(phonemeLookup[c])
	}
	return buf.String()
}

// lexPrefix uses a finite state machine to identify the next semantic sequence.
// It returns the byte length of the matched sequence, its replacement, and an elision flag.
// The declarative rules map the IAST inventory, while non-alphanumerics are naturally elided.
func lexPrefix(text string) (int, int, bool) {
	cursor, marker := 0, 0
	
//line "normalize.go":121
{
	var yych byte
	yyaccept := 0
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,'\t','\n','\v','\f','\r',0x0E,0x0F,0x10,0x11,0x12,0x13,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x1C,0x1D,0x1E,0x1F,' ','!','"','#','$','%','&':
		fallthrough
	case '(',')','*','+',',','-','.','/','0','1','2','3','4','5','6','7','8','9',':',';','<','=','>','?','@':
		fallthrough
	case 'F':
		fallthrough
	case 'Q':
		fallthrough
	case 'W','X':
		fallthrough
	case 'Z','[','\\',']','^','_','`':
		fallthrough
	case 'f':
		fallthrough
	case 'q':
		fallthrough
	case 'w','x':
		fallthrough
	case 'z','{','|','}','~',0x7F:
		goto yy1
	case '\'':
		goto yy2
	case 'A':
		fallthrough
	case 'a':
		goto yy4
	case 'B':
		fallthrough
	case 'b':
		goto yy5
	case 'C':
		fallthrough
	case 'c':
		goto yy7
	case 'D':
		fallthrough
	case 'd':
		goto yy9
	case 'E':
		fallthrough
	case 'e':
		goto yy11
	case 'G':
		fallthrough
	case 'g':
		goto yy12
	case 'H':
		goto yy14
	case 'I':
		fallthrough
	case 'i':
		goto yy16
	case 'J':
		fallthrough
	case 'j':
		goto yy17
	case 'K':
		fallthrough
	case 'k':
		goto yy19
	case 'L':
		fallthrough
	case 'l':
		goto yy21
	case 'M':
		fallthrough
	case 'm':
		goto yy23
	case 'N':
		fallthrough
	case 'n':
		goto yy25
	case 'O':
		fallthrough
	case 'o':
		goto yy26
	case 'P':
		fallthrough
	case 'p':
		goto yy27
	case 'R':
		fallthrough
	case 'r':
		goto yy29
	case 'S':
		fallthrough
	case 's':
		goto yy31
	case 'T':
		fallthrough
	case 't':
		goto yy32
	case 'U':
		fallthrough
	case 'u':
		goto yy34
	case 'V':
		fallthrough
	case 'v':
		goto yy35
	case 'Y':
		fallthrough
	case 'y':
		goto yy36
	case 'h':
		goto yy37
	case 0xC2:
		fallthrough
	case 0xC7,0xC8:
		fallthrough
	case 0xCA,0xCB,0xCC,0xCD,0xCE,0xCF,0xD0,0xD1,0xD2:
		fallthrough
	case 0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF:
		goto yy40
	case 0xC3:
		goto yy41
	case 0xC4:
		goto yy42
	case 0xC5:
		goto yy43
	case 0xC6:
		goto yy44
	case 0xC9:
		goto yy45
	case 0xD3:
		goto yy46
	case 0xE0:
		goto yy47
	case 0xE1:
		goto yy48
	case 0xE2:
		goto yy49
	case 0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xEB,0xEC,0xED,0xEE,0xEF:
		goto yy50
	case 0xF0:
		goto yy51
	case 0xF1,0xF2,0xF3:
		goto yy52
	case 0xF4:
		goto yy53
	default:
		goto yy38
	}
yy1:
	cursor++
//line "_normalize.re.go":209
	{
		r, _ := utf8.DecodeRuneInString(text[:cursor])
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			return cursor, Pnul, true
		}
		return cursor, Pother, false
	}
//line "normalize.go":280
yy2:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case '!':
		goto yy54
	default:
		goto yy3
	}
yy3:
//line "_normalize.re.go":148
	{ return cursor, Pa, false }
//line "normalize.go":293
yy4:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'I':
		fallthrough
	case 'i':
		goto yy55
	case 'U':
		fallthrough
	case 'u':
		goto yy56
	default:
		goto yy3
	}
yy5:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy57
	default:
		goto yy6
	}
yy6:
//line "_normalize.re.go":191
	{ return cursor, Pb, false }
//line "normalize.go":323
yy7:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy58
	default:
		goto yy8
	}
yy8:
//line "_normalize.re.go":174
	{ return cursor, Pc, false }
//line "normalize.go":338
yy9:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy59
	default:
		goto yy10
	}
yy10:
//line "_normalize.re.go":186
	{ return cursor, Pd, false }
//line "normalize.go":353
yy11:
	cursor++
//line "_normalize.re.go":158
	{ return cursor, Pe, false }
//line "normalize.go":358
yy12:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy60
	default:
		goto yy13
	}
yy13:
//line "_normalize.re.go":171
	{ return cursor, Pg, false }
//line "normalize.go":373
yy14:
	yyaccept = 0
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy61
	default:
		goto yy15
	}
yy15:
//line "_normalize.re.go":201
	{ return cursor, Ph, false }
//line "normalize.go":388
yy16:
	cursor++
//line "_normalize.re.go":150
	{ return cursor, Pi, false }
//line "normalize.go":393
yy17:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy63
	default:
		goto yy18
	}
yy18:
//line "_normalize.re.go":176
	{ return cursor, Pj, false }
//line "normalize.go":408
yy19:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy64
	default:
		goto yy20
	}
yy20:
//line "_normalize.re.go":169
	{ return cursor, Pk, false }
//line "normalize.go":423
yy21:
	yyaccept = 1
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy65
	default:
		goto yy22
	}
yy22:
//line "_normalize.re.go":196
	{ return cursor, Pl, false }
//line "normalize.go":438
yy23:
	yyaccept = 2
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy66
	default:
		goto yy24
	}
yy24:
//line "_normalize.re.go":193
	{ return cursor, Pm, false }
//line "normalize.go":453
yy25:
	cursor++
//line "_normalize.re.go":188
	{ return cursor, Pn, false }
//line "normalize.go":458
yy26:
	cursor++
//line "_normalize.re.go":160
	{ return cursor, Po, false }
//line "normalize.go":463
yy27:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy67
	default:
		goto yy28
	}
yy28:
//line "_normalize.re.go":189
	{ return cursor, Pp, false }
//line "normalize.go":478
yy29:
	yyaccept = 3
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy68
	default:
		goto yy30
	}
yy30:
//line "_normalize.re.go":195
	{ return cursor, Pr, false }
//line "normalize.go":493
yy31:
	cursor++
//line "_normalize.re.go":200
	{ return cursor, Ps, false }
//line "normalize.go":498
yy32:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy69
	default:
		goto yy33
	}
yy33:
//line "_normalize.re.go":184
	{ return cursor, Pt, false }
//line "normalize.go":513
yy34:
	cursor++
//line "_normalize.re.go":152
	{ return cursor, Pu, false }
//line "normalize.go":518
yy35:
	cursor++
//line "_normalize.re.go":197
	{ return cursor, Pv, false }
//line "normalize.go":523
yy36:
	cursor++
//line "_normalize.re.go":194
	{ return cursor, Py, false }
//line "normalize.go":528
yy37:
	cursor++
	goto yy15
yy38:
	cursor++
yy39:
//line "_normalize.re.go":125
	{ return 1, Pnul, true }
//line "normalize.go":537
yy40:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	default:
		goto yy39
	}
yy41:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90:
		fallthrough
	case 0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0:
		fallthrough
	case 0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x91:
		fallthrough
	case 0xB1:
		goto yy70
	default:
		goto yy39
	}
yy42:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81:
		goto yy71
	case 0x82,0x83:
		goto yy54
	case 0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93:
		fallthrough
	case 0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9:
		fallthrough
	case 0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x94,0x95:
		goto yy11
	case 0xAA,0xAB:
		goto yy72
	case 0xAC,0xAD:
		goto yy16
	default:
		goto yy39
	}
yy43:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D:
		fallthrough
	case 0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99:
		fallthrough
	case 0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9:
		fallthrough
	case 0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x8E,0x8F:
		goto yy26
	case 0x9A,0x9B:
		goto yy73
	case 0xAA,0xAB:
		goto yy74
	case 0xAC,0xAD:
		goto yy34
	default:
		goto yy39
	}
yy44:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E:
		fallthrough
	case 0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x8F:
		goto yy75
	default:
		goto yy39
	}
yy45:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98:
		fallthrough
	case 0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x99:
		goto yy75
	default:
		goto yy39
	}
yy46:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97:
		fallthrough
	case 0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x98,0x99:
		goto yy75
	default:
		goto yy39
	}
yy47:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy77
	default:
		goto yy39
	}
yy48:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7:
		fallthrough
	case 0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy77
	case 0xB8:
		goto yy78
	case 0xB9:
		goto yy79
	case 0xBA:
		goto yy80
	default:
		goto yy39
	}
yy49:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80:
		goto yy81
	case 0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy77
	default:
		goto yy39
	}
yy50:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy77
	default:
		goto yy39
	}
yy51:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy82
	default:
		goto yy39
	}
yy52:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy82
	default:
		goto yy39
	}
yy53:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F:
		goto yy82
	default:
		goto yy39
	}
yy54:
	cursor++
	goto yy3
yy55:
	cursor++
//line "_normalize.re.go":159
	{ return cursor, Pai, false }
//line "normalize.go":743
yy56:
	cursor++
//line "_normalize.re.go":161
	{ return cursor, Pau, false }
//line "normalize.go":748
yy57:
	cursor++
//line "_normalize.re.go":192
	{ return cursor, Pbh, false }
//line "normalize.go":753
yy58:
	cursor++
//line "_normalize.re.go":175
	{ return cursor, Pch, false }
//line "normalize.go":758
yy59:
	cursor++
//line "_normalize.re.go":187
	{ return cursor, Pdh, false }
//line "normalize.go":763
yy60:
	cursor++
//line "_normalize.re.go":172
	{ return cursor, Pgh, false }
//line "normalize.go":768
yy61:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xB1:
		goto yy83
	default:
		goto yy62
	}
yy62:
	cursor = marker
	switch (yyaccept) {
	case 0:
		goto yy15
	case 1:
		goto yy22
	case 2:
		goto yy24
	case 3:
		goto yy30
	case 4:
		goto yy39
	case 5:
		goto yy76
	case 6:
		goto yy85
	default:
		goto yy88
	}
yy63:
	cursor++
//line "_normalize.re.go":177
	{ return cursor, Pjh, false }
//line "normalize.go":802
yy64:
	cursor++
//line "_normalize.re.go":170
	{ return cursor, Pkh, false }
//line "normalize.go":807
yy65:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA5:
		goto yy84
	default:
		goto yy62
	}
yy66:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x83:
		fallthrough
	case 0x90:
		goto yy86
	default:
		goto yy62
	}
yy67:
	cursor++
//line "_normalize.re.go":190
	{ return cursor, Pph, false }
//line "normalize.go":832
yy68:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA5:
		goto yy87
	default:
		goto yy62
	}
yy69:
	cursor++
//line "_normalize.re.go":185
	{ return cursor, Pth, false }
//line "normalize.go":846
yy70:
	cursor++
//line "_normalize.re.go":178
	{ return cursor, Pñ, false }
//line "normalize.go":851
yy71:
	cursor++
//line "_normalize.re.go":149
	{ return cursor, Pā, false }
//line "normalize.go":856
yy72:
	cursor++
//line "_normalize.re.go":151
	{ return cursor, Pī, false }
//line "normalize.go":861
yy73:
	cursor++
//line "_normalize.re.go":198
	{ return cursor, Pś, false }
//line "normalize.go":866
yy74:
	cursor++
//line "_normalize.re.go":153
	{ return cursor, Pū, false }
//line "normalize.go":871
yy75:
	yyaccept = 5
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy89
	default:
		goto yy76
	}
yy76:
//line "_normalize.re.go":206
	{ return cursor, Pschwa, false }
//line "normalize.go":886
yy77:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	default:
		goto yy62
	}
yy78:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B:
		fallthrough
	case 0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3:
		fallthrough
	case 0xA6,0xA7,0xA8,0xA9:
		fallthrough
	case 0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5:
		fallthrough
	case 0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x8C,0x8D:
		goto yy90
	case 0xA4,0xA5:
		fallthrough
	case 0xAA,0xAB:
		goto yy83
	case 0xB6,0xB7:
		goto yy92
	case 0xB8,0xB9:
		goto yy93
	default:
		goto yy62
	}
yy79:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83:
		goto yy86
	case 0x84,0x85:
		goto yy94
	case 0x86,0x87:
		goto yy95
	case 0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99:
		fallthrough
	case 0x9E,0x9F,0xA0,0xA1:
		fallthrough
	case 0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB:
		fallthrough
	case 0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x9A,0x9B:
		goto yy96
	case 0x9C,0x9D:
		goto yy97
	case 0xA2,0xA3:
		goto yy98
	case 0xAC,0xAD:
		goto yy99
	default:
		goto yy62
	}
yy80:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95:
		fallthrough
	case 0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x96:
		goto yy83
	default:
		goto yy62
	}
yy81:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98:
		fallthrough
	case 0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x99:
		goto yy2
	default:
		goto yy62
	}
yy82:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy77
	default:
		goto yy62
	}
yy83:
	cursor++
//line "_normalize.re.go":167
	{ return cursor, Pḥ, false }
//line "normalize.go":991
yy84:
	yyaccept = 6
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy101
	default:
		goto yy85
	}
yy85:
//line "_normalize.re.go":156
	{ return cursor, Pḷ, false }
//line "normalize.go":1006
yy86:
	cursor++
//line "_normalize.re.go":164
	{ return cursor, Pṃ, false }
//line "normalize.go":1011
yy87:
	yyaccept = 7
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy102
	default:
		goto yy88
	}
yy88:
//line "_normalize.re.go":154
	{ return cursor, Pṛ, false }
//line "normalize.go":1026
yy89:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy103
	default:
		goto yy62
	}
yy90:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy104
	default:
		goto yy91
	}
yy91:
//line "_normalize.re.go":181
	{ return cursor, Pḍ, false }
//line "normalize.go":1050
yy92:
	cursor++
	goto yy85
yy93:
	cursor++
//line "_normalize.re.go":157
	{ return cursor, Pḹ, false }
//line "normalize.go":1058
yy94:
	cursor++
//line "_normalize.re.go":173
	{ return cursor, Pṅ, false }
//line "normalize.go":1063
yy95:
	cursor++
//line "_normalize.re.go":183
	{ return cursor, Pṇ, false }
//line "normalize.go":1068
yy96:
	cursor++
	goto yy88
yy97:
	cursor++
//line "_normalize.re.go":155
	{ return cursor, Pṝ, false }
//line "normalize.go":1076
yy98:
	cursor++
//line "_normalize.re.go":199
	{ return cursor, Pṣ, false }
//line "normalize.go":1081
yy99:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy105
	default:
		goto yy100
	}
yy100:
//line "_normalize.re.go":179
	{ return cursor, Pṭ, false }
//line "normalize.go":1096
yy101:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy93
	default:
		goto yy62
	}
yy102:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy97
	default:
		goto yy62
	}
yy103:
	cursor++
//line "_normalize.re.go":207
	{ return cursor, Plongschwa, false }
//line "normalize.go":1119
yy104:
	cursor++
//line "_normalize.re.go":182
	{ return cursor, Pḍh, false }
//line "normalize.go":1124
yy105:
	cursor++
//line "_normalize.re.go":180
	{ return cursor, Pṭh, false }
//line "normalize.go":1129
}
//line "_normalize.re.go":216

}

// consumeToken reads the next token and aligns the cursor with grapheme boundaries.
// It absorbs any trailing combining characters attached to the recognized sequence.
func consumeToken(text string) (int, int, bool) {
	matchLen, rep, elide := lexPrefix(text)
	consumed := 0
	state := -1
	rest := text
	for consumed < matchLen {
		var cluster string
		cluster, rest, _, state = uniseg.StepString(rest, state)
		consumed += len(cluster)
	}
	return consumed, rep, elide
}

// lexFormB applies second-order phonological transformations on the binary representation.
// It maps Form A sequences to a further reduced Form B logic.
func lexFormB(formA string) (int, int) {
	cursor, marker := 0, 0
	_ = marker
	
//line "normalize.go":1156
{
	var yych byte
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x00:
		goto yy107
	case 0x01,0x02:
		goto yy108
	case 0x03,0x04:
		goto yy109
	case 0x05,0x06:
		goto yy110
	case 0x07,0x08:
		goto yy111
	case '\t','\n':
		goto yy112
	case '\v':
		goto yy113
	case '\f':
		goto yy114
	case '\r':
		goto yy115
	case 0x0E:
		goto yy116
	case 0x0F:
		goto yy117
	case 0x10:
		goto yy119
	case 0x11:
		goto yy120
	case 0x12:
		fallthrough
	case 0x14:
		goto yy122
	case 0x13:
		goto yy123
	case 0x15:
		goto yy124
	case 0x16:
		goto yy125
	case 0x17:
		fallthrough
	case 0x19:
		goto yy127
	case 0x18:
		goto yy128
	case 0x1A:
		goto yy129
	case 0x1B:
		goto yy130
	case 0x1C:
		fallthrough
	case '!':
		fallthrough
	case '#':
		goto yy132
	case 0x1D:
		goto yy133
	case 0x1E:
		goto yy134
	case 0x1F:
		goto yy135
	case ' ':
		goto yy136
	case '"':
		goto yy137
	case '$':
		goto yy138
	case '%':
		goto yy139
	case '&':
		fallthrough
	case '(':
		goto yy141
	case '\'':
		goto yy142
	case ')':
		goto yy143
	case '*':
		goto yy144
	case '+':
		goto yy146
	case ',':
		goto yy148
	case '-':
		goto yy150
	case '.','/','0':
		goto yy152
	case '1':
		goto yy153
	case '2','3':
		goto yy154
	case '4':
		goto yy155
	default:
		goto yy156
	}
yy107:
	cursor++
//line "_normalize.re.go":249
	{ return 1, Pnul }
//line "normalize.go":1258
yy108:
	cursor++
//line "_normalize.re.go":308
	{ return cursor, Pa }
//line "normalize.go":1263
yy109:
	cursor++
//line "_normalize.re.go":309
	{ return cursor, Pi }
//line "normalize.go":1268
yy110:
	cursor++
//line "_normalize.re.go":310
	{ return cursor, Pu }
//line "normalize.go":1273
yy111:
	cursor++
//line "_normalize.re.go":311
	{ return cursor, Pṛ }
//line "normalize.go":1278
yy112:
	cursor++
//line "_normalize.re.go":312
	{ return cursor, Pḷ }
//line "normalize.go":1283
yy113:
	cursor++
//line "_normalize.re.go":313
	{ return cursor, Pe }
//line "normalize.go":1288
yy114:
	cursor++
//line "_normalize.re.go":314
	{ return cursor, Pai }
//line "normalize.go":1293
yy115:
	cursor++
//line "_normalize.re.go":315
	{ return cursor, Po }
//line "normalize.go":1298
yy116:
	cursor++
//line "_normalize.re.go":316
	{ return cursor, Pau }
//line "normalize.go":1303
yy117:
	cursor++
yy118:
//line "_normalize.re.go":319
	{ return cursor, Pn }
//line "normalize.go":1309
yy119:
	cursor++
//line "_normalize.re.go":317
	{ return cursor, Pḥ }
//line "normalize.go":1314
yy120:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x11,0x12:
		goto yy122
	default:
		goto yy121
	}
yy121:
//line "_normalize.re.go":318
	{ return cursor, Pk }
//line "normalize.go":1327
yy122:
	cursor++
	goto yy121
yy123:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x13,0x14:
		goto yy122
	default:
		goto yy121
	}
yy124:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x15:
		goto yy117
	default:
		goto yy118
	}
yy125:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x16,0x17:
		goto yy127
	default:
		goto yy126
	}
yy126:
//line "_normalize.re.go":320
	{ return cursor, Pc }
//line "normalize.go":1361
yy127:
	cursor++
	goto yy126
yy128:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x18,0x19:
		goto yy127
	default:
		goto yy126
	}
yy129:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x1A:
		goto yy117
	default:
		goto yy118
	}
yy130:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x1B,0x1C:
		goto yy132
	default:
		goto yy131
	}
yy131:
//line "_normalize.re.go":321
	{ return cursor, Pt }
//line "normalize.go":1395
yy132:
	cursor++
	goto yy131
yy133:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x1D:
		goto yy132
	default:
		goto yy131
	}
yy134:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x1E:
		goto yy132
	default:
		goto yy131
	}
yy135:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x1F:
		goto yy117
	default:
		goto yy118
	}
yy136:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case ' ','!':
		goto yy132
	default:
		goto yy131
	}
yy137:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case '"','#':
		goto yy132
	default:
		goto yy131
	}
yy138:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case '$':
		goto yy117
	default:
		goto yy118
	}
yy139:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case '%','&':
		goto yy141
	default:
		goto yy140
	}
yy140:
//line "_normalize.re.go":322
	{ return cursor, Pp }
//line "normalize.go":1465
yy141:
	cursor++
	goto yy140
yy142:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case '\'','(':
		goto yy141
	default:
		goto yy140
	}
yy143:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case ')':
		goto yy117
	default:
		goto yy118
	}
yy144:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case '*':
		goto yy157
	default:
		goto yy145
	}
yy145:
//line "_normalize.re.go":323
	{ return cursor, Py }
//line "normalize.go":1499
yy146:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case '+':
		goto yy158
	default:
		goto yy147
	}
yy147:
//line "_normalize.re.go":324
	{ return cursor, Pr }
//line "normalize.go":1512
yy148:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case ',':
		goto yy159
	default:
		goto yy149
	}
yy149:
//line "_normalize.re.go":325
	{ return cursor, Pl }
//line "normalize.go":1525
yy150:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case '-':
		goto yy160
	default:
		goto yy151
	}
yy151:
//line "_normalize.re.go":326
	{ return cursor, Pv }
//line "normalize.go":1538
yy152:
	cursor++
//line "_normalize.re.go":327
	{ return cursor, Ps }
//line "normalize.go":1543
yy153:
	cursor++
//line "_normalize.re.go":328
	{ return cursor, Ph }
//line "normalize.go":1548
yy154:
	cursor++
//line "_normalize.re.go":329
	{ return cursor, Pschwa }
//line "normalize.go":1553
yy155:
	cursor++
//line "_normalize.re.go":330
	{ return cursor, Pother }
//line "normalize.go":1558
yy156:
	cursor++
//line "_normalize.re.go":333
	{ return 1, int(formA[0]) }
//line "normalize.go":1563
yy157:
	cursor++
	goto yy145
yy158:
	cursor++
	goto yy147
yy159:
	cursor++
	goto yy149
yy160:
	cursor++
	goto yy151
}
//line "_normalize.re.go":334

}

// toFormA converts UTF-8 text to the internal Form A (binary phonemic sequence).
// It maintains alignment arrays for original start and end byte positions.
func toFormA(text string) (string, []int, []int) {
	var formA strings.Builder
	var starts, ends []int
	cursor := 0
	for len(text) > 0 {
		consumed, rep, elide := consumeToken(text)
		if elide {
			cursor += consumed
			text = text[consumed:]
			continue
		}
		endCursor := cursor + consumed
		starts = append(starts, cursor)
		ends = append(ends, endCursor)
		formA.WriteByte(byte(rep))
		cursor = endCursor
		text = text[consumed:]
	}
	return formA.String(), starts, ends
}

// toFormB converts Form A to Form B, applying phonological neutralizations.
// It returns the mapped binary sequence and its index boundaries within Form A.
func toFormB(formA string) (string, []int, []int) {
	var formB strings.Builder
	var starts, ends []int
	cursor := 0
	for len(formA) > 0 {
		consumed, rep := lexFormB(formA)
		if rep == Pnul {
			break
		}
		starts = append(starts, cursor)
		ends = append(ends, cursor+consumed)
		formB.WriteByte(byte(rep))
		cursor += consumed
		formA = formA[consumed:]
	}
	return formB.String(), starts, ends
}

// foldString provides the complete normalization pipeline from UTF-8 to Form B.
// It maintains the strict index synchronization required by the search engine.
func foldString(text string) (string, []int, []int) {
	formA, startsA, endsA := toFormA(text)
	formB, startsB, endsB := toFormB(formA)
	var finalStarts, finalEnds []int
	for i := 0; i < len(formB); i++ {
		finalStarts = append(finalStarts, startsA[startsB[i]])
		finalEnds = append(finalEnds, endsA[endsB[i]-1])
	}
	return formB, finalStarts, finalEnds
}
