// Code generated by re2c 3.1 on Mon Jun  1 18:46:24 2026, DO NOT EDIT.
//line "_normalize.re.go":1
//go:generate re2go -W -Werror -8 -o normalize.go _normalize.re.go

// XXX see if Arlo answered https://github.com/erc-dharma/project-documentation/issues/408.

package main

import (
	"log"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/rivo/uniseg"
)

// Dummy variables to prevent IDE formatters from stripping required imports.
var (
	_ = utf8.DecodeRuneInString
	_ = unicode.IsLetter
	_ = log.Fatalf
)

const (
	Pnul = iota
	Pa
	Pā
	Pi
	Pī
	Pu
	Pū
	Pṛ
	Pṝ
	Pḷ
	Pḹ
	Pe
	Pai
	Po
	Pau
	Pṃ
	Pḥ
	Pk
	Pkh
	Pg
	Pgh
	Pṅ
	Pc
	Pch
	Pj
	Pjh
	Pñ
	Pṭ
	Pṭh
	Pḍ
	Pḍh
	Pṇ
	Pt
	Pth
	Pd
	Pdh
	Pn
	Pp
	Pph
	Pb
	Pbh
	Pm
	Py
	Pr
	Pl
	Pv
	Pś
	Pṣ
	Ps
	Ph
	Pschwa
	Plongschwa
	Pother
)

var phonemeLookup = []string{
	"!",
	"a", "ā", "i", "ī", "u", "ū",
	"ṛ", "ṝ", "ḷ", "ḹ",
	"e", "ai", "o", "au",
	"ṃ", "ḥ",
	"k", "kh", "g", "gh", "ṅ",
	"c", "ch", "j", "jh", "ñ",
	"ṭ", "ṭh", "ḍ", "ḍh", "ṇ",
	"t", "th", "d", "dh", "n",
	"p", "ph", "b", "bh", "m",
	"y", "r", "l", "v",
	"ś", "ṣ", "s", "h",
	"ə", "ə̄",
	"?",
}

// peekByte safely reads a byte from a string to prevent out-of-bounds panics in re2c.
// It returns 0 when the cursor reaches or exceeds the string length.
func peekByte(s string, i int) byte {
	if i < len(s) {
		return s[i]
	}
	return 0
}

func makePrintable(s string) string {
	var buf strings.Builder
	for i := 0; i < len(s); i++ {
		c := int(s[i])
		buf.WriteString(phonemeLookup[c])
	}
	return buf.String()
}

// lexPrefix uses a finite state machine to identify the next semantic sequence.
// It returns the byte length of the matched sequence, its replacement, and an elision flag.
// The declarative rules map the IAST inventory, while non-alphanumerics are naturally elided.
func lexPrefix(text string) (int, int, bool) {
	cursor, marker := 0, 0
	
//line "normalize.go":123
{
	var yych byte
	yyaccept := 0
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,'\t','\n','\v','\f','\r',0x0E,0x0F,0x10,0x11,0x12,0x13,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x1C,0x1D,0x1E,0x1F,' ','!','"','#','$','%','&':
		fallthrough
	case '(',')','*','+',',','-','.','/','0','1','2','3','4','5','6','7','8','9',':',';','<','=','>','?','@':
		fallthrough
	case 'F':
		fallthrough
	case 'Q':
		fallthrough
	case 'W','X':
		fallthrough
	case 'Z','[','\\',']','^','_','`':
		fallthrough
	case 'f':
		fallthrough
	case 'q':
		fallthrough
	case 'w','x':
		fallthrough
	case 'z','{','|','}','~',0x7F:
		goto yy1
	case '\'':
		goto yy2
	case 'A':
		fallthrough
	case 'a':
		goto yy4
	case 'B':
		fallthrough
	case 'b':
		goto yy5
	case 'C':
		fallthrough
	case 'c':
		goto yy7
	case 'D':
		fallthrough
	case 'd':
		goto yy9
	case 'E':
		fallthrough
	case 'e':
		goto yy11
	case 'G':
		fallthrough
	case 'g':
		goto yy12
	case 'H':
		goto yy14
	case 'I':
		fallthrough
	case 'i':
		goto yy16
	case 'J':
		fallthrough
	case 'j':
		goto yy17
	case 'K':
		fallthrough
	case 'k':
		goto yy19
	case 'L':
		fallthrough
	case 'l':
		goto yy21
	case 'M':
		fallthrough
	case 'm':
		goto yy23
	case 'N':
		fallthrough
	case 'n':
		goto yy25
	case 'O':
		fallthrough
	case 'o':
		goto yy26
	case 'P':
		fallthrough
	case 'p':
		goto yy27
	case 'R':
		fallthrough
	case 'r':
		goto yy29
	case 'S':
		fallthrough
	case 's':
		goto yy31
	case 'T':
		fallthrough
	case 't':
		goto yy32
	case 'U':
		fallthrough
	case 'u':
		goto yy34
	case 'V':
		fallthrough
	case 'v':
		goto yy35
	case 'Y':
		fallthrough
	case 'y':
		goto yy36
	case 'h':
		goto yy37
	case 0xC2:
		fallthrough
	case 0xC7,0xC8:
		fallthrough
	case 0xCA,0xCB,0xCC,0xCD,0xCE,0xCF,0xD0,0xD1,0xD2:
		fallthrough
	case 0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF:
		goto yy40
	case 0xC3:
		goto yy41
	case 0xC4:
		goto yy42
	case 0xC5:
		goto yy43
	case 0xC6:
		goto yy44
	case 0xC9:
		goto yy45
	case 0xD3:
		goto yy46
	case 0xE0:
		goto yy47
	case 0xE1:
		goto yy48
	case 0xE2:
		goto yy49
	case 0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xEB,0xEC,0xED,0xEE,0xEF:
		goto yy50
	case 0xF0:
		goto yy51
	case 0xF1,0xF2,0xF3:
		goto yy52
	case 0xF4:
		goto yy53
	default:
		goto yy38
	}
yy1:
	cursor++
//line "_normalize.re.go":220
	{
		r, _ := utf8.DecodeRuneInString(text[:cursor])
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			return cursor, Pnul, true
		}
		return cursor, Pother, false
	}
//line "normalize.go":282
yy2:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case '!':
		goto yy54
	default:
		goto yy3
	}
yy3:
//line "_normalize.re.go":153
	{ return cursor, Pa, false }
//line "normalize.go":295
yy4:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'I':
		fallthrough
	case 'i':
		goto yy55
	case 'U':
		fallthrough
	case 'u':
		goto yy56
	default:
		goto yy3
	}
yy5:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy57
	default:
		goto yy6
	}
yy6:
//line "_normalize.re.go":199
	{ return cursor, Pb, false }
//line "normalize.go":325
yy7:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy58
	default:
		goto yy8
	}
yy8:
//line "_normalize.re.go":182
	{ return cursor, Pc, false }
//line "normalize.go":340
yy9:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy59
	default:
		goto yy10
	}
yy10:
//line "_normalize.re.go":194
	{ return cursor, Pd, false }
//line "normalize.go":355
yy11:
	cursor++
//line "_normalize.re.go":166
	{ return cursor, Pe, false }
//line "normalize.go":360
yy12:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy60
	default:
		goto yy13
	}
yy13:
//line "_normalize.re.go":179
	{ return cursor, Pg, false }
//line "normalize.go":375
yy14:
	yyaccept = 0
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy61
	default:
		goto yy15
	}
yy15:
//line "_normalize.re.go":209
	{ return cursor, Ph, false }
//line "normalize.go":390
yy16:
	cursor++
//line "_normalize.re.go":155
	{ return cursor, Pi, false }
//line "normalize.go":395
yy17:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy63
	default:
		goto yy18
	}
yy18:
//line "_normalize.re.go":184
	{ return cursor, Pj, false }
//line "normalize.go":410
yy19:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy64
	default:
		goto yy20
	}
yy20:
//line "_normalize.re.go":177
	{ return cursor, Pk, false }
//line "normalize.go":425
yy21:
	yyaccept = 1
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xC6:
		goto yy65
	case 0xC9:
		goto yy66
	case 0xCC:
		goto yy67
	case 0xD3:
		goto yy68
	default:
		goto yy22
	}
yy22:
//line "_normalize.re.go":204
	{ return cursor, Pl, false }
//line "normalize.go":446
yy23:
	yyaccept = 2
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy69
	default:
		goto yy24
	}
yy24:
//line "_normalize.re.go":201
	{ return cursor, Pm, false }
//line "normalize.go":461
yy25:
	cursor++
//line "_normalize.re.go":196
	{ return cursor, Pn, false }
//line "normalize.go":466
yy26:
	cursor++
//line "_normalize.re.go":168
	{ return cursor, Po, false }
//line "normalize.go":471
yy27:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy70
	default:
		goto yy28
	}
yy28:
//line "_normalize.re.go":197
	{ return cursor, Pp, false }
//line "normalize.go":486
yy29:
	yyaccept = 3
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xC6:
		goto yy71
	case 0xC9:
		goto yy72
	case 0xCC:
		goto yy73
	case 0xD3:
		goto yy74
	default:
		goto yy30
	}
yy30:
//line "_normalize.re.go":203
	{ return cursor, Pr, false }
//line "normalize.go":507
yy31:
	cursor++
//line "_normalize.re.go":208
	{ return cursor, Ps, false }
//line "normalize.go":512
yy32:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy75
	default:
		goto yy33
	}
yy33:
//line "_normalize.re.go":192
	{ return cursor, Pt, false }
//line "normalize.go":527
yy34:
	cursor++
//line "_normalize.re.go":157
	{ return cursor, Pu, false }
//line "normalize.go":532
yy35:
	cursor++
//line "_normalize.re.go":205
	{ return cursor, Pv, false }
//line "normalize.go":537
yy36:
	cursor++
//line "_normalize.re.go":202
	{ return cursor, Py, false }
//line "normalize.go":542
yy37:
	cursor++
	goto yy15
yy38:
	cursor++
yy39:
//line "_normalize.re.go":130
	{ return 1, Pnul, true }
//line "normalize.go":551
yy40:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	default:
		goto yy39
	}
yy41:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90:
		fallthrough
	case 0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0:
		fallthrough
	case 0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x91:
		fallthrough
	case 0xB1:
		goto yy76
	default:
		goto yy39
	}
yy42:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81:
		goto yy77
	case 0x82,0x83:
		goto yy54
	case 0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91:
		fallthrough
	case 0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9:
		fallthrough
	case 0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x92,0x93,0x94,0x95:
		goto yy11
	case 0xAA,0xAB:
		goto yy78
	case 0xAC,0xAD:
		goto yy16
	default:
		goto yy39
	}
yy43:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B:
		fallthrough
	case 0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99:
		fallthrough
	case 0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9:
		fallthrough
	case 0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x8C,0x8D,0x8E,0x8F:
		goto yy26
	case 0x9A,0x9B:
		goto yy79
	case 0xAA,0xAB:
		goto yy80
	case 0xAC,0xAD:
		goto yy34
	default:
		goto yy39
	}
yy44:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E:
		fallthrough
	case 0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x8F:
		goto yy81
	default:
		goto yy39
	}
yy45:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98:
		fallthrough
	case 0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x99:
		goto yy81
	default:
		goto yy39
	}
yy46:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97:
		fallthrough
	case 0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x98,0x99:
		goto yy81
	default:
		goto yy39
	}
yy47:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy83
	default:
		goto yy39
	}
yy48:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7:
		fallthrough
	case 0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy83
	case 0xB8:
		goto yy84
	case 0xB9:
		goto yy85
	case 0xBA:
		goto yy86
	default:
		goto yy39
	}
yy49:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80:
		goto yy87
	case 0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy83
	default:
		goto yy39
	}
yy50:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy83
	default:
		goto yy39
	}
yy51:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy88
	default:
		goto yy39
	}
yy52:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy88
	default:
		goto yy39
	}
yy53:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F:
		goto yy88
	default:
		goto yy39
	}
yy54:
	cursor++
	goto yy3
yy55:
	cursor++
//line "_normalize.re.go":167
	{ return cursor, Pai, false }
//line "normalize.go":757
yy56:
	cursor++
//line "_normalize.re.go":169
	{ return cursor, Pau, false }
//line "normalize.go":762
yy57:
	cursor++
//line "_normalize.re.go":200
	{ return cursor, Pbh, false }
//line "normalize.go":767
yy58:
	cursor++
//line "_normalize.re.go":183
	{ return cursor, Pch, false }
//line "normalize.go":772
yy59:
	cursor++
//line "_normalize.re.go":195
	{ return cursor, Pdh, false }
//line "normalize.go":777
yy60:
	cursor++
//line "_normalize.re.go":180
	{ return cursor, Pgh, false }
//line "normalize.go":782
yy61:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xB1:
		goto yy89
	default:
		goto yy62
	}
yy62:
	cursor = marker
	switch (yyaccept) {
	case 0:
		goto yy15
	case 1:
		goto yy22
	case 2:
		goto yy24
	case 3:
		goto yy30
	case 4:
		goto yy39
	case 5:
		goto yy82
	case 6:
		goto yy91
	default:
		goto yy95
	}
yy63:
	cursor++
//line "_normalize.re.go":185
	{ return cursor, Pjh, false }
//line "normalize.go":816
yy64:
	cursor++
//line "_normalize.re.go":178
	{ return cursor, Pkh, false }
//line "normalize.go":821
yy65:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x8F:
		goto yy90
	default:
		goto yy62
	}
yy66:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x99:
		goto yy90
	default:
		goto yy62
	}
yy67:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA5:
		goto yy92
	default:
		goto yy62
	}
yy68:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x98,0x99:
		goto yy90
	default:
		goto yy62
	}
yy69:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x83:
		fallthrough
	case 0x90:
		goto yy93
	default:
		goto yy62
	}
yy70:
	cursor++
//line "_normalize.re.go":198
	{ return cursor, Pph, false }
//line "normalize.go":873
yy71:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x8F:
		goto yy94
	default:
		goto yy62
	}
yy72:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x99:
		goto yy94
	default:
		goto yy62
	}
yy73:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA5:
		goto yy96
	default:
		goto yy62
	}
yy74:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x98,0x99:
		goto yy94
	default:
		goto yy62
	}
yy75:
	cursor++
//line "_normalize.re.go":193
	{ return cursor, Pth, false }
//line "normalize.go":914
yy76:
	cursor++
//line "_normalize.re.go":186
	{ return cursor, Pñ, false }
//line "normalize.go":919
yy77:
	cursor++
//line "_normalize.re.go":154
	{ return cursor, Pā, false }
//line "normalize.go":924
yy78:
	cursor++
//line "_normalize.re.go":156
	{ return cursor, Pī, false }
//line "normalize.go":929
yy79:
	cursor++
//line "_normalize.re.go":206
	{ return cursor, Pś, false }
//line "normalize.go":934
yy80:
	cursor++
//line "_normalize.re.go":158
	{ return cursor, Pū, false }
//line "normalize.go":939
yy81:
	yyaccept = 5
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case ':':
		goto yy97
	case 0xCC:
		goto yy98
	default:
		goto yy82
	}
yy82:
//line "_normalize.re.go":217
	{ return cursor, Pschwa, false }
//line "normalize.go":956
yy83:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	default:
		goto yy62
	}
yy84:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B:
		fallthrough
	case 0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3:
		fallthrough
	case 0xA6,0xA7,0xA8,0xA9:
		fallthrough
	case 0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5:
		fallthrough
	case 0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x8C,0x8D:
		goto yy99
	case 0xA4,0xA5:
		fallthrough
	case 0xAA,0xAB:
		goto yy89
	case 0xB6,0xB7:
		goto yy90
	case 0xB8,0xB9:
		goto yy101
	default:
		goto yy62
	}
yy85:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83:
		goto yy93
	case 0x84,0x85:
		goto yy102
	case 0x86,0x87:
		goto yy103
	case 0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99:
		fallthrough
	case 0x9E,0x9F,0xA0,0xA1:
		fallthrough
	case 0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB:
		fallthrough
	case 0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x9A,0x9B:
		goto yy94
	case 0x9C,0x9D:
		goto yy104
	case 0xA2,0xA3:
		goto yy105
	case 0xAC,0xAD:
		goto yy106
	default:
		goto yy62
	}
yy86:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95:
		fallthrough
	case 0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x96:
		goto yy89
	default:
		goto yy62
	}
yy87:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98:
		fallthrough
	case 0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x99:
		goto yy2
	default:
		goto yy62
	}
yy88:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy83
	default:
		goto yy62
	}
yy89:
	cursor++
//line "_normalize.re.go":175
	{ return cursor, Pḥ, false }
//line "normalize.go":1061
yy90:
	cursor++
yy91:
//line "_normalize.re.go":163
	{ return cursor, Pḷ, false }
//line "normalize.go":1067
yy92:
	yyaccept = 6
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy108
	default:
		goto yy91
	}
yy93:
	cursor++
//line "_normalize.re.go":172
	{ return cursor, Pṃ, false }
//line "normalize.go":1083
yy94:
	cursor++
yy95:
//line "_normalize.re.go":161
	{ return cursor, Pṛ, false }
//line "normalize.go":1089
yy96:
	yyaccept = 7
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy109
	default:
		goto yy95
	}
yy97:
	cursor++
	goto yy82
yy98:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy110
	default:
		goto yy62
	}
yy99:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy111
	default:
		goto yy100
	}
yy100:
//line "_normalize.re.go":189
	{ return cursor, Pḍ, false }
//line "normalize.go":1127
yy101:
	cursor++
//line "_normalize.re.go":164
	{ return cursor, Pḹ, false }
//line "normalize.go":1132
yy102:
	cursor++
//line "_normalize.re.go":181
	{ return cursor, Pṅ, false }
//line "normalize.go":1137
yy103:
	cursor++
//line "_normalize.re.go":191
	{ return cursor, Pṇ, false }
//line "normalize.go":1142
yy104:
	cursor++
//line "_normalize.re.go":162
	{ return cursor, Pṝ, false }
//line "normalize.go":1147
yy105:
	cursor++
//line "_normalize.re.go":207
	{ return cursor, Pṣ, false }
//line "normalize.go":1152
yy106:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy112
	default:
		goto yy107
	}
yy107:
//line "_normalize.re.go":187
	{ return cursor, Pṭ, false }
//line "normalize.go":1167
yy108:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy101
	default:
		goto yy62
	}
yy109:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy104
	default:
		goto yy62
	}
yy110:
	cursor++
//line "_normalize.re.go":218
	{ return cursor, Plongschwa, false }
//line "normalize.go":1190
yy111:
	cursor++
//line "_normalize.re.go":190
	{ return cursor, Pḍh, false }
//line "normalize.go":1195
yy112:
	cursor++
//line "_normalize.re.go":188
	{ return cursor, Pṭh, false }
//line "normalize.go":1200
}
//line "_normalize.re.go":227

}

// consumeToken reads the next token and aligns the cursor with grapheme boundaries.
// It absorbs any trailing combining characters attached to the recognized sequence.
func consumeToken(text string) (int, int, bool) {
	matchLen, rep, elide := lexPrefix(text)
	consumed := 0
	state := -1
	rest := text
	for consumed < matchLen {
		var cluster string
		cluster, rest, _, state = uniseg.StepString(rest, state)
		consumed += len(cluster)
	}
	return consumed, rep, elide
}

// lexFormB applies second-order phonological transformations on the binary representation.
// It maps Form A sequences to a further reduced Form B logic.
func lexFormB(formA string) (int, int) {
	cursor, marker := 0, 0
	_ = marker
	
//line "normalize.go":1227
{
	var yych byte
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x00:
		goto yy114
	case 0x01,0x02:
		goto yy115
	case 0x03,0x04:
		goto yy116
	case 0x05,0x06:
		goto yy117
	case 0x07,0x08:
		goto yy118
	case '\t','\n':
		goto yy119
	case '\v':
		goto yy120
	case '\f':
		goto yy121
	case '\r':
		goto yy122
	case 0x0E:
		goto yy123
	case 0x0F:
		goto yy124
	case 0x10:
		fallthrough
	case '1':
		goto yy126
	case 0x11:
		goto yy127
	case 0x12:
		fallthrough
	case 0x14:
		goto yy129
	case 0x13:
		goto yy130
	case 0x15:
		goto yy131
	case 0x16:
		goto yy132
	case 0x17:
		fallthrough
	case 0x19:
		goto yy134
	case 0x18:
		goto yy135
	case 0x1A:
		goto yy136
	case 0x1B:
		goto yy137
	case 0x1C:
		fallthrough
	case '!':
		fallthrough
	case '#':
		goto yy139
	case 0x1D:
		goto yy140
	case 0x1E:
		goto yy141
	case 0x1F:
		goto yy142
	case ' ':
		goto yy143
	case '"':
		goto yy144
	case '$':
		goto yy145
	case '%':
		goto yy146
	case '&':
		fallthrough
	case '(':
		goto yy148
	case '\'':
		goto yy149
	case ')':
		goto yy150
	case '*':
		goto yy151
	case '+':
		goto yy153
	case ',':
		goto yy155
	case '-':
		goto yy157
	case '.','/','0':
		goto yy159
	case '2','3':
		goto yy160
	case '4':
		goto yy161
	default:
		goto yy162
	}
yy114:
	cursor++
//line "_normalize.re.go":260
	{ return 1, Pnul }
//line "normalize.go":1329
yy115:
	cursor++
//line "_normalize.re.go":319
	{ return cursor, Pa }
//line "normalize.go":1334
yy116:
	cursor++
//line "_normalize.re.go":320
	{ return cursor, Pi }
//line "normalize.go":1339
yy117:
	cursor++
//line "_normalize.re.go":321
	{ return cursor, Pu }
//line "normalize.go":1344
yy118:
	cursor++
//line "_normalize.re.go":322
	{ return cursor, Pṛ }
//line "normalize.go":1349
yy119:
	cursor++
//line "_normalize.re.go":323
	{ return cursor, Pḷ }
//line "normalize.go":1354
yy120:
	cursor++
//line "_normalize.re.go":324
	{ return cursor, Pe }
//line "normalize.go":1359
yy121:
	cursor++
//line "_normalize.re.go":325
	{ return cursor, Pai }
//line "normalize.go":1364
yy122:
	cursor++
//line "_normalize.re.go":326
	{ return cursor, Po }
//line "normalize.go":1369
yy123:
	cursor++
//line "_normalize.re.go":327
	{ return cursor, Pau }
//line "normalize.go":1374
yy124:
	cursor++
yy125:
//line "_normalize.re.go":330
	{ return cursor, Pn }
//line "normalize.go":1380
yy126:
	cursor++
//line "_normalize.re.go":328
	{ return cursor, Ph }
//line "normalize.go":1385
yy127:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x11,0x12:
		goto yy129
	default:
		goto yy128
	}
yy128:
//line "_normalize.re.go":329
	{ return cursor, Pk }
//line "normalize.go":1398
yy129:
	cursor++
	goto yy128
yy130:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x13,0x14:
		goto yy129
	default:
		goto yy128
	}
yy131:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x15:
		goto yy124
	default:
		goto yy125
	}
yy132:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x16,0x17:
		goto yy134
	default:
		goto yy133
	}
yy133:
//line "_normalize.re.go":331
	{ return cursor, Pc }
//line "normalize.go":1432
yy134:
	cursor++
	goto yy133
yy135:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x18,0x19:
		goto yy134
	default:
		goto yy133
	}
yy136:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x1A:
		goto yy124
	default:
		goto yy125
	}
yy137:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x1B,0x1C:
		goto yy139
	default:
		goto yy138
	}
yy138:
//line "_normalize.re.go":332
	{ return cursor, Pt }
//line "normalize.go":1466
yy139:
	cursor++
	goto yy138
yy140:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x1D:
		goto yy139
	default:
		goto yy138
	}
yy141:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x1E:
		goto yy139
	default:
		goto yy138
	}
yy142:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x1F:
		goto yy124
	default:
		goto yy125
	}
yy143:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case ' ','!':
		goto yy139
	default:
		goto yy138
	}
yy144:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case '"','#':
		goto yy139
	default:
		goto yy138
	}
yy145:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case '$':
		goto yy124
	default:
		goto yy125
	}
yy146:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case '%','&':
		goto yy148
	default:
		goto yy147
	}
yy147:
//line "_normalize.re.go":333
	{ return cursor, Pp }
//line "normalize.go":1536
yy148:
	cursor++
	goto yy147
yy149:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case '\'','(':
		goto yy148
	default:
		goto yy147
	}
yy150:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case ')':
		goto yy124
	default:
		goto yy125
	}
yy151:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case '*':
		goto yy163
	default:
		goto yy152
	}
yy152:
//line "_normalize.re.go":334
	{ return cursor, Py }
//line "normalize.go":1570
yy153:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case '+':
		goto yy164
	default:
		goto yy154
	}
yy154:
//line "_normalize.re.go":335
	{ return cursor, Pr }
//line "normalize.go":1583
yy155:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case ',':
		goto yy165
	default:
		goto yy156
	}
yy156:
//line "_normalize.re.go":336
	{ return cursor, Pl }
//line "normalize.go":1596
yy157:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case '-':
		goto yy166
	default:
		goto yy158
	}
yy158:
//line "_normalize.re.go":337
	{ return cursor, Pv }
//line "normalize.go":1609
yy159:
	cursor++
//line "_normalize.re.go":338
	{ return cursor, Ps }
//line "normalize.go":1614
yy160:
	cursor++
//line "_normalize.re.go":339
	{ return cursor, Pschwa }
//line "normalize.go":1619
yy161:
	cursor++
//line "_normalize.re.go":340
	{ return cursor, Pother }
//line "normalize.go":1624
yy162:
	cursor++
//line "_normalize.re.go":343
	{ return 1, int(formA[0]) }
//line "normalize.go":1629
yy163:
	cursor++
	goto yy152
yy164:
	cursor++
	goto yy154
yy165:
	cursor++
	goto yy156
yy166:
	cursor++
	goto yy158
}
//line "_normalize.re.go":344

}

// toFormA converts UTF-8 text to the internal Form A (binary phonemic sequence).
// It maintains alignment arrays for original start and end byte positions.
func toFormA(text string) (string, []int, []int) {
	var formA strings.Builder
	var starts, ends []int
	cursor := 0
	for len(text) > 0 {
		consumed, rep, elide := consumeToken(text)
		if elide {
			cursor += consumed
			text = text[consumed:]
			continue
		}
		endCursor := cursor + consumed
		starts = append(starts, cursor)
		ends = append(ends, endCursor)
		formA.WriteByte(byte(rep))
		cursor = endCursor
		text = text[consumed:]
	}
	return formA.String(), starts, ends
}

// toFormB converts Form A to Form B, applying phonological neutralizations.
// It returns the mapped binary sequence and its index boundaries within Form A.
func toFormB(formA string) (string, []int, []int) {
	var formB strings.Builder
	var starts, ends []int
	cursor := 0
	for len(formA) > 0 {
		consumed, rep := lexFormB(formA)
		if rep == Pnul {
			break
		}
		starts = append(starts, cursor)
		ends = append(ends, cursor+consumed)
		formB.WriteByte(byte(rep))
		cursor += consumed
		formA = formA[consumed:]
	}
	return formB.String(), starts, ends
}

// foldString provides the complete normalization pipeline from UTF-8 to Form B.
// It maintains the strict index synchronization required by the search engine.
func foldString(text string) (string, []int, []int) {
	formA, startsA, endsA := toFormA(text)
	formB, startsB, endsB := toFormB(formA)
	var finalStarts, finalEnds []int
	for i := 0; i < len(formB); i++ {
		finalStarts = append(finalStarts, startsA[startsB[i]])
		finalEnds = append(finalEnds, endsA[endsB[i]-1])
	}
	return formB, finalStarts, finalEnds
}
