// Code generated by re2c 3.1 on Tue Jun  2 16:46:55 2026, DO NOT EDIT.
//line "_normalize.re.go":1
//go:generate re2go -W -Werror -8 -o normalize.go _normalize.re.go

package main

import (
	"log"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/rivo/uniseg"
	"golang.org/x/text/cases"
)

// Dummy variables to prevent IDE formatters from stripping required imports.
var (
	_ = utf8.DecodeRuneInString
	_ = unicode.IsLetter
	_ = log.Fatalf
	_ = cases.Fold
)

const (
	Pnul = iota
	Pa
	Pā
	Pi
	Pī
	Pu
	Pū
	Pṛ
	Pṝ
	Pḷ
	Pḹ
	Pe
	Pai
	Po
	Pau
	Pṃ
	Pḥ
	Pk
	Pkh
	Pg
	Pgh
	Pṅ
	Pc
	Pch
	Pj
	Pjh
	Pñ
	Pṭ
	Pṭh
	Pḍ
	Pḍh
	Pṇ
	Pt
	Pth
	Pd
	Pdh
	Pn
	Pp
	Pph
	Pb
	Pbh
	Pm
	Py
	Pr
	Pl
	Pv
	Pś
	Pṣ
	Ps
	Ph
	Pschwa
	Plongschwa
	Pother
)

var phonemeLookup = []string{
	"!",
	"a", "ā", "i", "ī", "u", "ū",
	"ṛ", "ṝ", "ḷ", "ḹ",
	"e", "ai", "o", "au",
	"ṃ", "ḥ",
	"k", "kh", "g", "gh", "ṅ",
	"c", "ch", "j", "jh", "ñ",
	"ṭ", "ṭh", "ḍ", "ḍh", "ṇ",
	"t", "th", "d", "dh", "n",
	"p", "ph", "b", "bh", "m",
	"y", "r", "l", "v",
	"ś", "ṣ", "s", "h",
	"ə", "ə̄",
	"?",
}

// peekByte safely reads a byte from a string to prevent out-of-bounds panics in re2c.
// It returns 0 when the cursor reaches or exceeds the string length.
func peekByte(s string, i int) byte {
	if i < len(s) {
		return s[i]
	}
	return 0
}

// makePrintable converts the internal binary representation back to readable characters.
// It maps sequence codes to their IAST equivalents for debugging purposes.
func makePrintable(s string) string {
	var buf strings.Builder
	for i := 0; i < len(s); i++ {
		c := int(s[i])
		buf.WriteString(phonemeLookup[c])
	}
	return buf.String()
}

// lexPrefix uses a finite state machine to identify the next semantic sequence.
// It returns the byte length of the matched sequence, its replacement, and an elision flag.
func lexPrefix(text string) (int, int, bool) {
	cursor, marker := 0, 0
	
//line "normalize.go":124
{
	var yych byte
	yyaccept := 0
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,'\t','\n','\v','\f','\r',0x0E,0x0F,0x10,0x11,0x12,0x13,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x1C,0x1D,0x1E,0x1F,' ','!','"','#','$','%','&':
		fallthrough
	case '(',')','*','+',',','-','.','/','0','1','2','3','4','5','6','7','8','9',':',';','<','=','>','?','@':
		fallthrough
	case 'F':
		fallthrough
	case 'Q':
		fallthrough
	case 'W','X':
		fallthrough
	case 'Z','[','\\',']','^','_','`':
		fallthrough
	case 'f':
		fallthrough
	case 'q':
		fallthrough
	case 'w','x':
		fallthrough
	case 'z','{','|','}','~',0x7F:
		goto yy1
	case '\'':
		goto yy2
	case 'A':
		fallthrough
	case 'a':
		goto yy4
	case 'B':
		fallthrough
	case 'b':
		goto yy5
	case 'C':
		fallthrough
	case 'c':
		goto yy7
	case 'D':
		fallthrough
	case 'd':
		goto yy9
	case 'E':
		fallthrough
	case 'e':
		goto yy11
	case 'G':
		fallthrough
	case 'g':
		goto yy12
	case 'H':
		goto yy14
	case 'I':
		fallthrough
	case 'i':
		goto yy16
	case 'J':
		fallthrough
	case 'j':
		goto yy17
	case 'K':
		fallthrough
	case 'k':
		goto yy19
	case 'L':
		fallthrough
	case 'l':
		goto yy21
	case 'M':
		fallthrough
	case 'm':
		goto yy23
	case 'N':
		fallthrough
	case 'n':
		goto yy25
	case 'O':
		fallthrough
	case 'o':
		goto yy26
	case 'P':
		fallthrough
	case 'p':
		goto yy27
	case 'R':
		fallthrough
	case 'r':
		goto yy29
	case 'S':
		fallthrough
	case 's':
		goto yy31
	case 'T':
		fallthrough
	case 't':
		goto yy32
	case 'U':
		fallthrough
	case 'u':
		goto yy34
	case 'V':
		fallthrough
	case 'v':
		goto yy35
	case 'Y':
		fallthrough
	case 'y':
		goto yy36
	case 'h':
		goto yy37
	case 0xC2:
		fallthrough
	case 0xC7,0xC8:
		fallthrough
	case 0xCA,0xCB,0xCC,0xCD,0xCE,0xCF,0xD0,0xD1,0xD2:
		fallthrough
	case 0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF:
		goto yy40
	case 0xC3:
		goto yy41
	case 0xC4:
		goto yy42
	case 0xC5:
		goto yy43
	case 0xC6:
		goto yy44
	case 0xC9:
		goto yy45
	case 0xD3:
		goto yy46
	case 0xE0:
		goto yy47
	case 0xE1:
		goto yy48
	case 0xE2:
		goto yy49
	case 0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xEB,0xEC,0xED,0xEE,0xEF:
		goto yy50
	case 0xF0:
		goto yy51
	case 0xF1,0xF2,0xF3:
		goto yy52
	case 0xF4:
		goto yy53
	default:
		goto yy38
	}
yy1:
	cursor++
//line "_normalize.re.go":201
	{
		r, _ := utf8.DecodeRuneInString(text[:cursor])
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			return cursor, Pnul, true
		}
		return cursor, Pother, false
	}
//line "normalize.go":283
yy2:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case '!':
		goto yy54
	default:
		goto yy3
	}
yy3:
//line "_normalize.re.go":145
	{ return cursor, Pa, false }
//line "normalize.go":296
yy4:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'I':
		fallthrough
	case 'i':
		goto yy55
	case 'U':
		fallthrough
	case 'u':
		goto yy56
	default:
		goto yy3
	}
yy5:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy57
	default:
		goto yy6
	}
yy6:
//line "_normalize.re.go":185
	{ return cursor, Pb, false }
//line "normalize.go":326
yy7:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy58
	default:
		goto yy8
	}
yy8:
//line "_normalize.re.go":168
	{ return cursor, Pc, false }
//line "normalize.go":341
yy9:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy59
	default:
		goto yy10
	}
yy10:
//line "_normalize.re.go":180
	{ return cursor, Pd, false }
//line "normalize.go":356
yy11:
	cursor++
//line "_normalize.re.go":155
	{ return cursor, Pe, false }
//line "normalize.go":361
yy12:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy60
	default:
		goto yy13
	}
yy13:
//line "_normalize.re.go":165
	{ return cursor, Pg, false }
//line "normalize.go":376
yy14:
	yyaccept = 0
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy61
	default:
		goto yy15
	}
yy15:
//line "_normalize.re.go":195
	{ return cursor, Ph, false }
//line "normalize.go":391
yy16:
	cursor++
//line "_normalize.re.go":147
	{ return cursor, Pi, false }
//line "normalize.go":396
yy17:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy63
	default:
		goto yy18
	}
yy18:
//line "_normalize.re.go":170
	{ return cursor, Pj, false }
//line "normalize.go":411
yy19:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy64
	default:
		goto yy20
	}
yy20:
//line "_normalize.re.go":163
	{ return cursor, Pk, false }
//line "normalize.go":426
yy21:
	yyaccept = 1
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy65
	default:
		goto yy22
	}
yy22:
//line "_normalize.re.go":190
	{ return cursor, Pl, false }
//line "normalize.go":441
yy23:
	yyaccept = 2
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy66
	default:
		goto yy24
	}
yy24:
//line "_normalize.re.go":187
	{ return cursor, Pm, false }
//line "normalize.go":456
yy25:
	cursor++
//line "_normalize.re.go":182
	{ return cursor, Pn, false }
//line "normalize.go":461
yy26:
	cursor++
//line "_normalize.re.go":157
	{ return cursor, Po, false }
//line "normalize.go":466
yy27:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy67
	default:
		goto yy28
	}
yy28:
//line "_normalize.re.go":183
	{ return cursor, Pp, false }
//line "normalize.go":481
yy29:
	yyaccept = 3
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy68
	default:
		goto yy30
	}
yy30:
//line "_normalize.re.go":189
	{ return cursor, Pr, false }
//line "normalize.go":496
yy31:
	cursor++
//line "_normalize.re.go":194
	{ return cursor, Ps, false }
//line "normalize.go":501
yy32:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy69
	default:
		goto yy33
	}
yy33:
//line "_normalize.re.go":178
	{ return cursor, Pt, false }
//line "normalize.go":516
yy34:
	cursor++
//line "_normalize.re.go":149
	{ return cursor, Pu, false }
//line "normalize.go":521
yy35:
	cursor++
//line "_normalize.re.go":191
	{ return cursor, Pv, false }
//line "normalize.go":526
yy36:
	cursor++
//line "_normalize.re.go":188
	{ return cursor, Py, false }
//line "normalize.go":531
yy37:
	cursor++
	goto yy15
yy38:
	cursor++
yy39:
//line "_normalize.re.go":128
	{ return 1, Pnul, true }
//line "normalize.go":540
yy40:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	default:
		goto yy39
	}
yy41:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90:
		fallthrough
	case 0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0:
		fallthrough
	case 0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x91:
		fallthrough
	case 0xB1:
		goto yy70
	default:
		goto yy39
	}
yy42:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81:
		goto yy71
	case 0x82,0x83:
		goto yy54
	case 0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93:
		fallthrough
	case 0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9:
		fallthrough
	case 0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x94,0x95:
		goto yy11
	case 0xAA,0xAB:
		goto yy72
	case 0xAC,0xAD:
		goto yy16
	default:
		goto yy39
	}
yy43:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D:
		fallthrough
	case 0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99:
		fallthrough
	case 0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9:
		fallthrough
	case 0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x8E,0x8F:
		goto yy26
	case 0x9A,0x9B:
		goto yy73
	case 0xAA,0xAB:
		goto yy74
	case 0xAC,0xAD:
		goto yy34
	default:
		goto yy39
	}
yy44:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E:
		fallthrough
	case 0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x8F:
		goto yy75
	default:
		goto yy39
	}
yy45:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98:
		fallthrough
	case 0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x99:
		goto yy75
	default:
		goto yy39
	}
yy46:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97:
		fallthrough
	case 0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x98,0x99:
		goto yy75
	default:
		goto yy39
	}
yy47:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy77
	default:
		goto yy39
	}
yy48:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7:
		fallthrough
	case 0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy77
	case 0xB8:
		goto yy78
	case 0xB9:
		goto yy79
	case 0xBA:
		goto yy80
	default:
		goto yy39
	}
yy49:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80:
		goto yy81
	case 0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy77
	default:
		goto yy39
	}
yy50:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy77
	default:
		goto yy39
	}
yy51:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy82
	default:
		goto yy39
	}
yy52:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy82
	default:
		goto yy39
	}
yy53:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F:
		goto yy82
	default:
		goto yy39
	}
yy54:
	cursor++
	goto yy3
yy55:
	cursor++
//line "_normalize.re.go":156
	{ return cursor, Pai, false }
//line "normalize.go":746
yy56:
	cursor++
//line "_normalize.re.go":158
	{ return cursor, Pau, false }
//line "normalize.go":751
yy57:
	cursor++
//line "_normalize.re.go":186
	{ return cursor, Pbh, false }
//line "normalize.go":756
yy58:
	cursor++
//line "_normalize.re.go":169
	{ return cursor, Pch, false }
//line "normalize.go":761
yy59:
	cursor++
//line "_normalize.re.go":181
	{ return cursor, Pdh, false }
//line "normalize.go":766
yy60:
	cursor++
//line "_normalize.re.go":166
	{ return cursor, Pgh, false }
//line "normalize.go":771
yy61:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xB1:
		goto yy83
	default:
		goto yy62
	}
yy62:
	cursor = marker
	switch (yyaccept) {
	case 0:
		goto yy15
	case 1:
		goto yy22
	case 2:
		goto yy24
	case 3:
		goto yy30
	case 4:
		goto yy39
	case 5:
		goto yy76
	case 6:
		goto yy85
	default:
		goto yy88
	}
yy63:
	cursor++
//line "_normalize.re.go":171
	{ return cursor, Pjh, false }
//line "normalize.go":805
yy64:
	cursor++
//line "_normalize.re.go":164
	{ return cursor, Pkh, false }
//line "normalize.go":810
yy65:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA5:
		goto yy84
	default:
		goto yy62
	}
yy66:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x83:
		fallthrough
	case 0x90:
		goto yy86
	default:
		goto yy62
	}
yy67:
	cursor++
//line "_normalize.re.go":184
	{ return cursor, Pph, false }
//line "normalize.go":835
yy68:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA5:
		goto yy87
	default:
		goto yy62
	}
yy69:
	cursor++
//line "_normalize.re.go":179
	{ return cursor, Pth, false }
//line "normalize.go":849
yy70:
	cursor++
//line "_normalize.re.go":172
	{ return cursor, Pñ, false }
//line "normalize.go":854
yy71:
	cursor++
//line "_normalize.re.go":146
	{ return cursor, Pā, false }
//line "normalize.go":859
yy72:
	cursor++
//line "_normalize.re.go":148
	{ return cursor, Pī, false }
//line "normalize.go":864
yy73:
	cursor++
//line "_normalize.re.go":192
	{ return cursor, Pś, false }
//line "normalize.go":869
yy74:
	cursor++
//line "_normalize.re.go":150
	{ return cursor, Pū, false }
//line "normalize.go":874
yy75:
	yyaccept = 5
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy89
	default:
		goto yy76
	}
yy76:
//line "_normalize.re.go":199
	{ return cursor, Pschwa, false }
//line "normalize.go":889
yy77:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	default:
		goto yy62
	}
yy78:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B:
		fallthrough
	case 0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3:
		fallthrough
	case 0xA6,0xA7,0xA8,0xA9:
		fallthrough
	case 0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5:
		fallthrough
	case 0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x8C,0x8D:
		goto yy90
	case 0xA4,0xA5:
		fallthrough
	case 0xAA,0xAB:
		goto yy83
	case 0xB6,0xB7:
		goto yy92
	case 0xB8,0xB9:
		goto yy93
	default:
		goto yy62
	}
yy79:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83:
		goto yy86
	case 0x84,0x85:
		goto yy94
	case 0x86,0x87:
		goto yy95
	case 0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99:
		fallthrough
	case 0x9E,0x9F,0xA0,0xA1:
		fallthrough
	case 0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB:
		fallthrough
	case 0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x9A,0x9B:
		goto yy96
	case 0x9C,0x9D:
		goto yy97
	case 0xA2,0xA3:
		goto yy98
	case 0xAC,0xAD:
		goto yy99
	default:
		goto yy62
	}
yy80:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95:
		fallthrough
	case 0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x96:
		goto yy83
	default:
		goto yy62
	}
yy81:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98:
		fallthrough
	case 0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x99:
		goto yy2
	default:
		goto yy62
	}
yy82:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy77
	default:
		goto yy62
	}
yy83:
	cursor++
//line "_normalize.re.go":162
	{ return cursor, Pḥ, false }
//line "normalize.go":994
yy84:
	yyaccept = 6
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy101
	default:
		goto yy85
	}
yy85:
//line "_normalize.re.go":153
	{ return cursor, Pḷ, false }
//line "normalize.go":1009
yy86:
	cursor++
//line "_normalize.re.go":160
	{ return cursor, Pṃ, false }
//line "normalize.go":1014
yy87:
	yyaccept = 7
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy102
	default:
		goto yy88
	}
yy88:
//line "_normalize.re.go":151
	{ return cursor, Pṛ, false }
//line "normalize.go":1029
yy89:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy103
	default:
		goto yy62
	}
yy90:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy104
	default:
		goto yy91
	}
yy91:
//line "_normalize.re.go":175
	{ return cursor, Pḍ, false }
//line "normalize.go":1053
yy92:
	cursor++
	goto yy85
yy93:
	cursor++
//line "_normalize.re.go":154
	{ return cursor, Pḹ, false }
//line "normalize.go":1061
yy94:
	cursor++
//line "_normalize.re.go":167
	{ return cursor, Pṅ, false }
//line "normalize.go":1066
yy95:
	cursor++
//line "_normalize.re.go":177
	{ return cursor, Pṇ, false }
//line "normalize.go":1071
yy96:
	cursor++
	goto yy88
yy97:
	cursor++
//line "_normalize.re.go":152
	{ return cursor, Pṝ, false }
//line "normalize.go":1079
yy98:
	cursor++
//line "_normalize.re.go":193
	{ return cursor, Pṣ, false }
//line "normalize.go":1084
yy99:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy105
	default:
		goto yy100
	}
yy100:
//line "_normalize.re.go":173
	{ return cursor, Pṭ, false }
//line "normalize.go":1099
yy101:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy93
	default:
		goto yy62
	}
yy102:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy97
	default:
		goto yy62
	}
yy103:
	cursor++
//line "_normalize.re.go":200
	{ return cursor, Plongschwa, false }
//line "normalize.go":1122
yy104:
	cursor++
//line "_normalize.re.go":176
	{ return cursor, Pḍh, false }
//line "normalize.go":1127
yy105:
	cursor++
//line "_normalize.re.go":174
	{ return cursor, Pṭh, false }
//line "normalize.go":1132
}
//line "_normalize.re.go":208

}

// consumeToken reads the next token and aligns the cursor with grapheme boundaries.
// It absorbs any trailing combining characters attached to the recognized sequence.
func consumeToken(text string) (int, int, bool) {
	matchLen, rep, elide := lexPrefix(text)
	consumed := 0
	state := -1
	rest := text
	for consumed < matchLen {
		var cluster string
		cluster, rest, _, state = uniseg.StepString(rest, state)
		consumed += len(cluster)
	}
	return consumed, rep, elide
}

// lexFormB applies second-order phonological transformations on the binary representation.
// It maps Form A sequences to a further reduced Form B logic.
func lexFormB(formA string) (int, int) {
	cursor, marker := 0, 0
	_ = marker
	
//line "normalize.go":1159
{
	var yych byte
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x00:
		goto yy107
	case 0x01,0x02:
		goto yy108
	case 0x03,0x04:
		goto yy109
	case 0x05,0x06:
		goto yy110
	case 0x07,0x08:
		goto yy111
	case '\t','\n':
		goto yy112
	case '\v':
		goto yy113
	case '\f':
		goto yy114
	case '\r':
		goto yy115
	case 0x0E:
		goto yy116
	case 0x0F:
		goto yy117
	case 0x10:
		fallthrough
	case '1':
		goto yy119
	case 0x11:
		goto yy120
	case 0x12:
		fallthrough
	case 0x14:
		goto yy122
	case 0x13:
		goto yy123
	case 0x15:
		goto yy124
	case 0x16:
		goto yy125
	case 0x17:
		fallthrough
	case 0x19:
		goto yy127
	case 0x18:
		goto yy128
	case 0x1A:
		goto yy129
	case 0x1B:
		goto yy130
	case 0x1C:
		fallthrough
	case 0x1E:
		fallthrough
	case '!':
		fallthrough
	case '#':
		goto yy132
	case 0x1D:
		goto yy133
	case 0x1F:
		goto yy134
	case ' ':
		goto yy135
	case '"':
		goto yy136
	case '$':
		goto yy137
	case '%':
		goto yy138
	case '&':
		fallthrough
	case '(':
		goto yy140
	case '\'':
		goto yy141
	case ')':
		goto yy142
	case '*':
		goto yy143
	case '+':
		goto yy145
	case ',':
		goto yy147
	case '-':
		goto yy149
	case '.','/','0':
		goto yy151
	case '2','3':
		goto yy152
	case '4':
		goto yy153
	default:
		goto yy154
	}
yy107:
	cursor++
//line "_normalize.re.go":240
	{ return 1, Pnul }
//line "normalize.go":1261
yy108:
	cursor++
//line "_normalize.re.go":296
	{ return cursor, Pa }
//line "normalize.go":1266
yy109:
	cursor++
//line "_normalize.re.go":297
	{ return cursor, Pi }
//line "normalize.go":1271
yy110:
	cursor++
//line "_normalize.re.go":298
	{ return cursor, Pu }
//line "normalize.go":1276
yy111:
	cursor++
//line "_normalize.re.go":299
	{ return cursor, Pṛ }
//line "normalize.go":1281
yy112:
	cursor++
//line "_normalize.re.go":300
	{ return cursor, Pḷ }
//line "normalize.go":1286
yy113:
	cursor++
//line "_normalize.re.go":301
	{ return cursor, Pe }
//line "normalize.go":1291
yy114:
	cursor++
//line "_normalize.re.go":302
	{ return cursor, Pai }
//line "normalize.go":1296
yy115:
	cursor++
//line "_normalize.re.go":303
	{ return cursor, Po }
//line "normalize.go":1301
yy116:
	cursor++
//line "_normalize.re.go":304
	{ return cursor, Pau }
//line "normalize.go":1306
yy117:
	cursor++
yy118:
//line "_normalize.re.go":307
	{ return cursor, Pn }
//line "normalize.go":1312
yy119:
	cursor++
//line "_normalize.re.go":305
	{ return cursor, Ph }
//line "normalize.go":1317
yy120:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x11,0x12:
		goto yy122
	default:
		goto yy121
	}
yy121:
//line "_normalize.re.go":306
	{ return cursor, Pk }
//line "normalize.go":1330
yy122:
	cursor++
	goto yy121
yy123:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x13,0x14:
		goto yy122
	default:
		goto yy121
	}
yy124:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x15:
		goto yy117
	default:
		goto yy118
	}
yy125:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x16,0x17:
		goto yy127
	default:
		goto yy126
	}
yy126:
//line "_normalize.re.go":308
	{ return cursor, Pc }
//line "normalize.go":1364
yy127:
	cursor++
	goto yy126
yy128:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x18,0x19:
		goto yy127
	default:
		goto yy126
	}
yy129:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x1A:
		goto yy117
	default:
		goto yy118
	}
yy130:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x1B,0x1C:
		goto yy132
	default:
		goto yy131
	}
yy131:
//line "_normalize.re.go":309
	{ return cursor, Pt }
//line "normalize.go":1398
yy132:
	cursor++
	goto yy131
yy133:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x1D,0x1E:
		goto yy132
	default:
		goto yy131
	}
yy134:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case 0x1F:
		goto yy117
	default:
		goto yy118
	}
yy135:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case ' ','!':
		goto yy132
	default:
		goto yy131
	}
yy136:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case '"','#':
		goto yy132
	default:
		goto yy131
	}
yy137:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case '$':
		goto yy117
	default:
		goto yy118
	}
yy138:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case '%','&':
		goto yy140
	default:
		goto yy139
	}
yy139:
//line "_normalize.re.go":310
	{ return cursor, Pp }
//line "normalize.go":1459
yy140:
	cursor++
	goto yy139
yy141:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case '\'','(':
		goto yy140
	default:
		goto yy139
	}
yy142:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case ')':
		goto yy117
	default:
		goto yy118
	}
yy143:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case '*':
		goto yy155
	default:
		goto yy144
	}
yy144:
//line "_normalize.re.go":311
	{ return cursor, Py }
//line "normalize.go":1493
yy145:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case '+':
		goto yy156
	default:
		goto yy146
	}
yy146:
//line "_normalize.re.go":312
	{ return cursor, Pr }
//line "normalize.go":1506
yy147:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case ',':
		goto yy157
	default:
		goto yy148
	}
yy148:
//line "_normalize.re.go":313
	{ return cursor, Pl }
//line "normalize.go":1519
yy149:
	cursor++
	yych = peekByte(formA, cursor)
	switch (yych) {
	case '-':
		goto yy158
	default:
		goto yy150
	}
yy150:
//line "_normalize.re.go":314
	{ return cursor, Pv }
//line "normalize.go":1532
yy151:
	cursor++
//line "_normalize.re.go":315
	{ return cursor, Ps }
//line "normalize.go":1537
yy152:
	cursor++
//line "_normalize.re.go":316
	{ return cursor, Pschwa }
//line "normalize.go":1542
yy153:
	cursor++
//line "_normalize.re.go":317
	{ return cursor, Pother }
//line "normalize.go":1547
yy154:
	cursor++
//line "_normalize.re.go":319
	{ return 1, int(formA[0]) }
//line "normalize.go":1552
yy155:
	cursor++
	goto yy144
yy156:
	cursor++
	goto yy146
yy157:
	cursor++
	goto yy148
yy158:
	cursor++
	goto yy150
}
//line "_normalize.re.go":320

}

// toFormA converts UTF-8 text to the internal Form A without allocating bounds.
// It is optimized for high-speed evaluation during the filtering phase.
func toFormA(text string) string {
	var formA strings.Builder
	for len(text) > 0 {
		consumed, rep, elide := consumeToken(text)
		if elide {
			text = text[consumed:]
			continue
		}
		formA.WriteByte(byte(rep))
		text = text[consumed:]
	}
	return formA.String()
}

// toFormAWithBounds converts text to Form A and returns an interleaved bounds array.
// The array alternates original start and original end indices for each byte.
func toFormAWithBounds(text string) (string, []int) {
	var formA strings.Builder
	var bounds []int
	cursor := 0
	for len(text) > 0 {
		consumed, rep, elide := consumeToken(text)
		if elide {
			cursor += consumed
			text = text[consumed:]
			continue
		}
		endCursor := cursor + consumed
		formA.WriteByte(byte(rep))
		bounds = append(bounds, cursor, endCursor)
		cursor = endCursor
		text = text[consumed:]
	}
	return formA.String(), bounds
}

// toFormB converts Form A to Form B without calculating positional bounds.
// It applies phonological neutralizations strictly for content matching.
func toFormB(formA string) string {
	var formB strings.Builder
	for len(formA) > 0 {
		consumed, rep := lexFormB(formA)
		if rep == Pnul {
			break
		}
		formB.WriteByte(byte(rep))
		formA = formA[consumed:]
	}
	return formB.String()
}

// toFormBWithBounds converts Form A to Form B and maintains sequence bounds.
// It maps the reduced byte sequence back to its boundaries within Form A.
func toFormBWithBounds(formA string) (string, []int) {
	var formB strings.Builder
	var bounds []int
	cursor := 0
	for len(formA) > 0 {
		consumed, rep := lexFormB(formA)
		if rep == Pnul {
			break
		}
		formB.WriteByte(byte(rep))
		bounds = append(bounds, cursor, cursor+consumed)
		cursor += consumed
		formA = formA[consumed:]
	}
	return formB.String(), bounds
}

const normalFirst = 0xE002
const Slongschwa = string(normalFirst + Plongschwa)

var folder = cases.Fold()

// lexNormalPrefix uses a finite state machine to identify the next sequence for normal mode.
// It returns the byte length of the matched sequence, its replacement string, and an elision flag.
func lexNormalPrefix(text string) (int, string, bool) {
	cursor, marker := 0, 0
	
//line "normalize.go":1652
{
	var yych byte
	yyaccept := 0
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,'\t','\n','\v','\f','\r',0x0E,0x0F,0x10,0x11,0x12,0x13,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x1C,0x1D,0x1E,0x1F,' ','!','"','#','$','%','&','\'','(',')','*','+',',','-','.','/','0','1','2','3','4','5','6','7','8','9',':',';','<','=','>','?','@','A','B','C','D','E','F','G','H','I','J','K':
		fallthrough
	case 'M','N','O','P','Q':
		fallthrough
	case 'S','T','U','V','W','X','Y','Z','[','\\',']','^','_','`','a','b','c','d','e','f','g','h','i','j','k':
		fallthrough
	case 'm','n','o','p','q':
		fallthrough
	case 's','t','u','v','w','x','y','z','{','|','}','~',0x7F:
		goto yy160
	case 'L':
		fallthrough
	case 'l':
		goto yy162
	case 'R':
		fallthrough
	case 'r':
		goto yy163
	case 0xC2:
		fallthrough
	case 0xC7,0xC8:
		fallthrough
	case 0xCA,0xCB,0xCC,0xCD,0xCE,0xCF,0xD0,0xD1,0xD2:
		fallthrough
	case 0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF:
		goto yy166
	case 0xC3:
		goto yy167
	case 0xC4:
		goto yy168
	case 0xC5:
		goto yy169
	case 0xC6:
		goto yy170
	case 0xC9:
		goto yy171
	case 0xD3:
		goto yy172
	case 0xE0:
		goto yy173
	case 0xE1,0xE2,0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xEB,0xEC,0xED,0xEE,0xEF:
		goto yy174
	case 0xF0:
		goto yy175
	case 0xF1,0xF2,0xF3:
		goto yy176
	case 0xF4:
		goto yy177
	default:
		goto yy164
	}
yy160:
	cursor++
yy161:
//line "_normalize.re.go":423
	{
		r, size := utf8.DecodeRuneInString(text)
		return size, folder.String(string(r)), false
	}
//line "normalize.go":1717
yy162:
	yyaccept = 0
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy178
	default:
		goto yy161
	}
yy163:
	yyaccept = 0
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy180
	default:
		goto yy161
	}
yy164:
	cursor++
yy165:
//line "_normalize.re.go":412
	{ return 1, "", true }
//line "normalize.go":1745
yy166:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy160
	default:
		goto yy165
	}
yy167:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85:
		fallthrough
	case 0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5:
		fallthrough
	case 0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy160
	case 0x86:
		fallthrough
	case 0xA6:
		goto yy181
	default:
		goto yy165
	}
yy168:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F:
		fallthrough
	case 0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy160
	case 0x90,0x91:
		goto yy182
	default:
		goto yy165
	}
yy169:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91:
		fallthrough
	case 0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy160
	case 0x92,0x93:
		goto yy183
	default:
		goto yy165
	}
yy170:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E:
		fallthrough
	case 0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy160
	case 0x8F:
		goto yy184
	default:
		goto yy165
	}
yy171:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98:
		fallthrough
	case 0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy160
	case 0x99:
		goto yy184
	default:
		goto yy165
	}
yy172:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97:
		fallthrough
	case 0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy160
	case 0x98,0x99:
		goto yy185
	default:
		goto yy165
	}
yy173:
	yyaccept = 1
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy187
	default:
		goto yy165
	}
yy174:
	yyaccept = 1
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy187
	default:
		goto yy165
	}
yy175:
	yyaccept = 1
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy188
	default:
		goto yy165
	}
yy176:
	yyaccept = 1
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy188
	default:
		goto yy165
	}
yy177:
	yyaccept = 1
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F:
		goto yy188
	default:
		goto yy165
	}
yy178:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA5:
		goto yy189
	default:
		goto yy179
	}
yy179:
	cursor = marker
	switch (yyaccept) {
	case 0:
		goto yy161
	case 1:
		goto yy165
	case 2:
		goto yy186
	case 3:
		goto yy190
	default:
		goto yy192
	}
yy180:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA5:
		goto yy191
	default:
		goto yy179
	}
yy181:
	cursor++
//line "_normalize.re.go":414
	{ return cursor, "ae", false }
//line "normalize.go":1928
yy182:
	cursor++
//line "_normalize.re.go":415
	{ return cursor, "d", false }
//line "normalize.go":1933
yy183:
	cursor++
//line "_normalize.re.go":413
	{ return cursor, "oe", false }
//line "normalize.go":1938
yy184:
	yyaccept = 0
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy193
	default:
		goto yy161
	}
yy185:
	yyaccept = 2
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy193
	default:
		goto yy186
	}
yy186:
//line "_normalize.re.go":420
	{ return cursor, "ə", false }
//line "normalize.go":1964
yy187:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy160
	default:
		goto yy179
	}
yy188:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy187
	default:
		goto yy179
	}
yy189:
	yyaccept = 3
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy194
	default:
		goto yy190
	}
yy190:
//line "_normalize.re.go":418
	{ return cursor, "ḷ", false }
//line "normalize.go":1997
yy191:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy195
	default:
		goto yy192
	}
yy192:
//line "_normalize.re.go":416
	{ return cursor, "ṛ", false }
//line "normalize.go":2012
yy193:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy196
	default:
		goto yy179
	}
yy194:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy197
	default:
		goto yy179
	}
yy195:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy198
	default:
		goto yy179
	}
yy196:
	cursor++
//line "_normalize.re.go":421
	{ return cursor, Slongschwa, false }
//line "normalize.go":2044
yy197:
	cursor++
//line "_normalize.re.go":419
	{ return cursor, "ḹ", false }
//line "normalize.go":2049
yy198:
	cursor++
//line "_normalize.re.go":417
	{ return cursor, "ṝ", false }
//line "normalize.go":2054
}
//line "_normalize.re.go":427

}

// consumeNormalToken reads the next token for normal mode and aligns with grapheme boundaries.
// It attaches any trailing combining characters to the replacement string.
func consumeNormalToken(text string) (int, string, bool) {
	matchLen, rep, elide := lexNormalPrefix(text)
	consumed := 0
	state := -1
	rest := text
	for consumed < matchLen {
		var cluster string
		cluster, rest, _, state = uniseg.StepString(rest, state)
		consumed += len(cluster)
	}
	if consumed > matchLen && !elide {
		rep += text[matchLen:consumed]
	}
	return consumed, rep, elide
}

// transformNormal applies transformations for normal matching without allocating memory bounds.
// This fast path is crucial for eliminating garbage collection overhead during filtering.
func transformNormal(text string) string {
	var folded strings.Builder
	for len(text) > 0 {
		consumed, rep, elide := consumeNormalToken(text)
		if elide {
			text = text[consumed:]
			continue
		}
		folded.WriteString(rep)
		text = text[consumed:]
	}
	return folded.String()
}

// transformNormalWithBounds applies transformations and records interleaved index bounds.
// The returned array stores the exact original start and end byte offsets.
func transformNormalWithBounds(text string) (string, []int) {
	var folded strings.Builder
	var bounds []int
	cursor := 0
	for len(text) > 0 {
		consumed, rep, elide := consumeNormalToken(text)
		if elide {
			cursor += consumed
			text = text[consumed:]
			continue
		}
		endCursor := cursor + consumed
		n := len(rep)
		for j := 0; j < n; j++ {
			bounds = append(bounds, cursor, endCursor)
		}
		folded.WriteString(rep)
		cursor = endCursor
		text = text[consumed:]
	}
	return folded.String(), bounds
}

// transformNormalized executes the complete Form B pipeline purely for content evaluation.
// It bypasses the generation of transitive index bounds to conserve memory.
func transformNormalized(text string) string {
	return toFormB(toFormA(text))
}

// transformNormalizedWithBounds tracks structural limits across the double normalization.
// It recursively retrieves the initial offsets from Form A using the boundaries of Form B.
func transformNormalizedWithBounds(text string) (string, []int) {
	formA, boundsA := toFormAWithBounds(text)
	formB, boundsB := toFormBWithBounds(formA)
	var finalBounds []int
	for i := 0; i < len(formB); i++ {
		startA := boundsB[2*i]
		endA := boundsB[2*i+1] - 1
		finalBounds = append(finalBounds, boundsA[2*startA], boundsA[2*endA+1])
	}
	return formB, finalBounds
}

// transform acts as a fast text dispatcher ignoring positional metadata.
// It is intended for boolean evaluation matrices.
func transform(text string, mode string) string {
	if mode == "normalized" {
		return transformNormalized(text)
	}
	return transformNormal(text)
}

// transformWithBounds computes structural offsets alongside textual mapping.
// It is strictly reserved for the final highlight processing layer.
func transformWithBounds(text string, mode string) (string, []int) {
	if mode == "normalized" {
		return transformNormalizedWithBounds(text)
	}
	return transformNormalWithBounds(text)
}
