#!/usr/bin/env python3.8
# @generated by pegen from query_parser.g

import ast
import sys
import tokenize

from typing import Any, Optional

from pegen.parser import memoize, memoize_left_rec, logger, Parser


class Node:

	pass

class And(Node):

	def __init__(self, *children):
		self.children = list(children)

	def __repr__(self):
		buf = "(and "
		sep = ""
		for child in self.children:
			buf += sep + repr(child)
			sep = " "
		buf += ")"
		return buf

	def _complete_fields(self, name, mode=None):
		for i, child in enumerate(self.children):
			self.children[i] = child._complete_fields(name, mode)
		return self

	def serialize(self):
		return {
			"op": "and",
			"args": [c.serialize() for c in self.children],
		}

class Or(Node):

	def __init__(self, *children):
		self.children = list(children)

	def __repr__(self):
		buf = "(or "
		sep = ""
		for child in self.children:
			buf += sep + repr(child)
			sep = " "
		buf += ")"
		return buf

	def _complete_fields(self, name, mode=None):
		for i, child in enumerate(self.children):
			self.children[i] = child._complete_fields(name, mode)
		return self

	def serialize(self):
		return {
			"op": "or",
			"args": [c.serialize() for c in self.children],
		}

class Not(Node):

	def __init__(self, child=None):
		self.child = child

	def __repr__(self):
		buf = "(not "
		buf += repr(self.child)
		buf += ")"
		return buf

	def _complete_fields(self, name, mode=None):
		self.child = self.child._complete_fields(name, mode)
		return self

	def serialize(self):
		return {"op": "not", "arg": self.child.serialize()}

class Seq(Node):

	def __init__(self, left, right, x=0, y=-1):
		self.left = left
		self.right = right
		self.x = x
		self.y = y

	def __repr__(self):
		return f"(seq [{self.x}-{self.y}] {self.left!r} {self.right!r})"

	def _complete_fields(self, name, mode=None):
		# Validate that sequence operands are strictly textual leaves or nested sequences
		for child in (self.left, self.right):
			if not isinstance(child, (Field, Seq, Near)):
				raise ValueError("SEQ operands must be simple strings")
			if isinstance(child, Field) and child.name is not None:
				raise ValueError("SEQ operands cannot have explicit fields")
		self.left = self.left._complete_fields(name, mode)
		self.right = self.right._complete_fields(name, mode)
		return self

	def serialize(self):
		return {
			"op": "seq",
			"x": self.x,
			"y": self.y,
			"args": [self.left.serialize(), self.right.serialize()],
		}

class Near(Node):

	def __init__(self, left, right, x=0, y=-1):
		self.left = left
		self.right = right
		self.x = x
		self.y = y

	def __repr__(self):
		return f"(near [{self.x}-{self.y}] {self.left!r} {self.right!r})"

	def _complete_fields(self, name, mode=None):
		# Validate that near operands conform to adjacency constraints
		for child in (self.left, self.right):
			if not isinstance(child, (Field, Seq, Near)):
				raise ValueError("NEAR operands must be simple strings")
			if isinstance(child, Field) and child.name is not None:
				raise ValueError("NEAR operands cannot have explicit fields")
		self.left = self.left._complete_fields(name, mode)
		self.right = self.right._complete_fields(name, mode)
		return self

	def serialize(self):
		return {
			"op": "near",
			"x": self.x,
			"y": self.y,
			"args": [self.left.serialize(), self.right.serialize()],
		}

class Field(Node):

	def __init__(self, name, child=None, mode=None):
		self.name = name
		self.mode = mode
		self.child = child

	def __repr__(self):
		mode_str = f"[{self.mode}]" if self.mode else ""
		return f"{self.name or '<null>'}{mode_str}:{self.child!r}"

	def _resolve_name_mode(self, name, mode):
		# Extracted helper to keep functions short and modular
		final_name = self.name if self.name is not None else name
		final_mode = self.mode or mode
		if final_name:
			parts = final_name.split('.')
			if len(parts) > 1 and parts[-1] in {"normal", "exact", "normalized"}:
				final_mode = parts.pop()
			final_name = ".".join(parts)
		return final_name, final_mode

	def _expand_virtual(self, name, mode):
		# Extracted virtual field conditional checks to stay under length limits
		if name == "repo":
			return Or(Field("repo_id", self.child, mode), Field("repo_name", self.child, mode))
		if name == "author":
			return Or(Field("author_ident", self.child, mode), Field("author_name", self.child, mode))
		if name == "editor":
			return Or(Field("editor_ident", self.child, mode), Field("editor_name", self.child, mode))
		if name == "lang":
			return Or(Field("lang_ident", self.child, mode), Field("lang_name", self.child, mode))
		if name == "script":
			return Or(Field("script_ident", self.child, mode), Field("script_name", self.child, mode))
		return None

	def _complete_fields(self, name, mode=None):
		# Process name and mode using resolution and expansion helper functions
		final_name, final_mode = self._resolve_name_mode(name, mode)
		virtual_node = self._expand_virtual(final_name, final_mode)
		if virtual_node:
			return virtual_node._complete_fields("", None)
		mapping = {
			"repo.ident": "repo_id",
			"repo.name": "repo_name",
			"author.ident": "author_ident",
			"author.name": "author_name",
			"editor.ident": "editor_ident",
			"editor.name": "editor_name",
			"lang.ident": "lang_ident",
			"lang.name": "lang_name",
			"script.ident": "script_ident",
			"script.name": "script_name"
		}
		self.name = mapping.get(final_name, final_name)
		self.mode = final_mode
		if not isinstance(self.child, str):
			self.child = self.child._complete_fields("", final_mode)
		return self

	def serialize(self):
		# Serialize field node nesting sub-query if child is a logical node object
		res = {
			"op": "field",
			"field": self.name,
		}
		if isinstance(self.child, Node):
			res["arg"] = self.child.serialize()
		else:
			res["value"] = self.child
		if self.mode:
			res["mode"] = self.mode
		return res

class _Null(Node):

	def __repr__(self):
		return "<null>"

	def _complete_fields(self, name, mode=None):
		return self

	def serialize(self):
		return {"op": "null"}

Null = _Null()

def parse_distance(s):
	# Extract and parse a numeric distance from a string or node
	try:
		if hasattr(s, "string"): s = s.string
		clean_s = str(s).replace("/", "").strip()
		return (0, int(clean_s))
	except (ValueError, TypeError):
		return (0, -1)

def mkbinop(klass, l, r):
	# Instantiate or append to a binary operation node
	if isinstance(l, klass):
		l.children.append(r)
		return l
	return klass(l, r)

def mkand(*elems):
	# Generate an AND logical node
	return mkbinop(And, *elems)

def mkor(*elems):
	# Generate an OR logical node
	return mkbinop(Or, *elems)

def mkmerge(*elems):
	# Merge multiple logical elements correctly
	match len(elems):
		case 0:
			return Null
		case 1:
			return elems[0]
		case 2:
			return mkand(*elems)
		case _:
			return And(*elems)


# Keywords and soft keywords are listed at the end of the parser definition.
class GeneratedParser(Parser):

    @memoize
    def start(self) -> Optional[Any]:
        # start: Exprs $
        mark = self._mark()
        if (
            (r := self.Exprs())
            and
            (self.expect('ENDMARKER'))
        ):
            return r . _complete_fields ( "" , None );
        self._reset(mark)
        return None;

    @memoize
    def Exprs(self) -> Optional[Any]:
        # Exprs: Expr*
        # nullable=True
        mark = self._mark()
        if (
            (r := self._loop0_1(),)
        ):
            return mkmerge ( * r );
        self._reset(mark)
        return None;

    @memoize
    def Expr(self) -> Optional[Any]:
        # Expr: OrExpr
        mark = self._mark()
        if (
            (OrExpr := self.OrExpr())
        ):
            return OrExpr;
        self._reset(mark)
        return None;

    @memoize
    def FieldExpr(self) -> Optional[Any]:
        # FieldExpr: FieldName (':' | '=') PrimaryExpr | PrimaryExpr
        mark = self._mark()
        if (
            (name := self.FieldName())
            and
            (self._tmp_2())
            and
            (r := self.PrimaryExpr())
        ):
            return Field ( name , r );
        self._reset(mark)
        if (
            (PrimaryExpr := self.PrimaryExpr())
        ):
            return PrimaryExpr;
        self._reset(mark)
        return None;

    @memoize
    def PrimaryExpr(self) -> Optional[Any]:
        # PrimaryExpr: '(' Exprs ')' | Text
        mark = self._mark()
        if (
            (self.expect('('))
            and
            (r := self.Exprs())
            and
            (self.expect(')'))
        ):
            return r;
        self._reset(mark)
        if (
            (r := self.Text())
        ):
            return Field ( None , r );
        self._reset(mark)
        return None;

    @memoize_left_rec
    def OrExpr(self) -> Optional[Any]:
        # OrExpr: OrExpr 'OR' AndExpr | AndExpr
        mark = self._mark()
        if (
            (r := self.OrExpr())
            and
            (self.expect('OR'))
            and
            (s := self.AndExpr())
        ):
            return mkor ( r , s );
        self._reset(mark)
        if (
            (AndExpr := self.AndExpr())
        ):
            return AndExpr;
        self._reset(mark)
        return None;

    @memoize_left_rec
    def AndExpr(self) -> Optional[Any]:
        # AndExpr: AndExpr 'AND' NotExpr | NotExpr
        mark = self._mark()
        if (
            (r := self.AndExpr())
            and
            (self.expect('AND'))
            and
            (s := self.NotExpr())
        ):
            return mkand ( r , s );
        self._reset(mark)
        if (
            (NotExpr := self.NotExpr())
        ):
            return NotExpr;
        self._reset(mark)
        return None;

    @memoize
    def NotExpr(self) -> Optional[Any]:
        # NotExpr: 'NOT' NotExpr | NearExpr
        mark = self._mark()
        if (
            (self.expect('NOT'))
            and
            (r := self.NotExpr())
        ):
            return Not ( r );
        self._reset(mark)
        if (
            (NearExpr := self.NearExpr())
        ):
            return NearExpr;
        self._reset(mark)
        return None;

    @memoize_left_rec
    def NearExpr(self) -> Optional[Any]:
        # NearExpr: NearExpr NearOp SeqExpr | SeqExpr
        mark = self._mark()
        if (
            (r := self.NearExpr())
            and
            (op := self.NearOp())
            and
            (s := self.SeqExpr())
        ):
            return Near ( r , s , op [0] , op [1] );
        self._reset(mark)
        if (
            (SeqExpr := self.SeqExpr())
        ):
            return SeqExpr;
        self._reset(mark)
        return None;

    @memoize
    def NearOp(self) -> Optional[Any]:
        # NearOp: 'NEAR' "/" NUMBER | 'NEAR'
        mark = self._mark()
        if (
            (self.expect('NEAR'))
            and
            (self.expect("/"))
            and
            (dist := self.number())
        ):
            return parse_distance ( dist . string );
        self._reset(mark)
        if (
            (self.expect('NEAR'))
        ):
            return ( 0 , - 1 );
        self._reset(mark)
        return None;

    @memoize_left_rec
    def SeqExpr(self) -> Optional[Any]:
        # SeqExpr: SeqExpr SeqOp FieldExpr | FieldExpr
        mark = self._mark()
        if (
            (r := self.SeqExpr())
            and
            (op := self.SeqOp())
            and
            (s := self.FieldExpr())
        ):
            return Seq ( r , s , op [0] , op [1] );
        self._reset(mark)
        if (
            (FieldExpr := self.FieldExpr())
        ):
            return FieldExpr;
        self._reset(mark)
        return None;

    @memoize
    def SeqOp(self) -> Optional[Any]:
        # SeqOp: 'SEQ' "/" NUMBER | 'SEQ'
        mark = self._mark()
        if (
            (self.expect('SEQ'))
            and
            (self.expect("/"))
            and
            (dist := self.number())
        ):
            return parse_distance ( dist . string );
        self._reset(mark)
        if (
            (self.expect('SEQ'))
        ):
            return ( 0 , - 1 );
        self._reset(mark)
        return None;

    @memoize
    def Text(self) -> Optional[Any]:
        # Text: DottedName
        mark = self._mark()
        if (
            (r := self.DottedName())
        ):
            return r;
        self._reset(mark)
        return None;

    @memoize
    def FieldName(self) -> Optional[Any]:
        # FieldName: '.' DottedName | DottedName
        mark = self._mark()
        if (
            (self.expect('.'))
            and
            (r := self.DottedName())
        ):
            return "." + r;
        self._reset(mark)
        if (
            (DottedName := self.DottedName())
        ):
            return DottedName;
        self._reset(mark)
        return None;

    @memoize
    def DottedName(self) -> Optional[Any]:
        # DottedName: NAME '.' DottedName | NAME
        mark = self._mark()
        if (
            (r := self.name())
            and
            (self.expect('.'))
            and
            (s := self.DottedName())
        ):
            return r . string + "." + s;
        self._reset(mark)
        if (
            (r := self.name())
        ):
            return r . string;
        self._reset(mark)
        return None;

    @memoize
    def _loop0_1(self) -> Optional[Any]:
        # _loop0_1: Expr
        mark = self._mark()
        children = []
        while (
            (Expr := self.Expr())
        ):
            children.append(Expr)
            mark = self._mark()
        self._reset(mark)
        return children;

    @memoize
    def _tmp_2(self) -> Optional[Any]:
        # _tmp_2: ':' | '='
        mark = self._mark()
        if (
            (literal := self.expect(':'))
        ):
            return literal;
        self._reset(mark)
        if (
            (literal := self.expect('='))
        ):
            return literal;
        self._reset(mark)
        return None;

    KEYWORDS = ('AND', 'NEAR', 'NOT', 'OR', 'SEQ')
    SOFT_KEYWORDS = ()


if __name__ == '__main__':
    from pegen.parser import simple_parser_main
    simple_parser_main(GeneratedParser)
