// Code generated by re2c 3.1 on Wed Jun 24 12:25:02 2026, DO NOT EDIT.
//line "search/normalize.re.go":1


package main

import (
	"log"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/rivo/uniseg"
	"golang.org/x/text/cases"
)

// Dummy variables to prevent IDE formatters from stripping required imports.
var (
	_ = utf8.DecodeRuneInString
	_ = unicode.IsLetter
	_ = log.Fatalf
	_ = cases.Fold
)

const (
	Pnul = iota
	Pa
	Pā
	Pi
	Pī
	Pu
	Pū
	Pṛ
	Pṝ
	Pḷ
	Pḹ
	Pe
	Pai
	Po
	Pau
	Pṃ
	Pḥ
	Pk
	Pkh
	Pg
	Pgh
	Pṅ
	Pc
	Pch
	Pj
	Pjh
	Pñ
	Pṭ
	Pṭh
	Pḍ
	Pḍh
	Pṇ
	Pt
	Pth
	Pd
	Pdh
	Pn
	Pp
	Pph
	Pb
	Pbh
	Pm
	Py
	Pr
	Pl
	Pv
	Pś
	Pṣ
	Ps
	Ph
	Pschwa
	Plongschwa
	Pother
)

var phonemeLookup = []string{
	"!",
	"a", "ā", "i", "ī", "u", "ū",
	"ṛ", "ṝ", "ḷ", "ḹ",
	"e", "ai", "o", "au",
	"ṃ", "ḥ",
	"k", "kh", "g", "gh", "ṅ",
	"c", "ch", "j", "jh", "ñ",
	"ṭ", "ṭh", "ḍ", "ḍh", "ṇ",
	"t", "th", "d", "dh", "n",
	"p", "ph", "b", "bh", "m",
	"y", "r", "l", "v",
	"ś", "ṣ", "s", "h",
	"ə", "ə̄",
	"?",
}

// peekByte safely reads a byte from a string to prevent out-of-bounds panics in re2c.
// It returns 0 when the cursor reaches or exceeds the string length.
func peekByte(s string, i int) byte {
	if i < len(s) {
		return s[i]
	}
	return 0
}

// makePrintable converts the internal binary representation back to readable characters.
// It maps sequence codes to their IAST equivalents for debugging purposes.
func makePrintable(s string) string {
	var buf strings.Builder
	for i := 0; i < len(s); i++ {
		c := int(s[i])
		buf.WriteString(phonemeLookup[c])
	}
	return buf.String()
}

// lexPrefix uses a finite state machine to identify the next semantic sequence.
// It returns the byte length of the matched sequence, its replacement, and an elision flag.
func lexPrefix(text string) (int, int, bool) {
	cursor, marker := 0, 0
	_ = cursor
	_ = marker
	
//line "<stdout>":126
{
	var yych byte
	yyaccept := 0
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,'\t','\n','\v','\f','\r',0x0E,0x0F,0x10,0x11,0x12,0x13,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x1C,0x1D,0x1E,0x1F,' ','!','"','#','$','%','&':
		fallthrough
	case '(',')','*','+',',','-','.','/','0','1','2','3','4','5','6','7','8','9',':',';','<','=','>','?','@':
		fallthrough
	case 'F':
		fallthrough
	case 'Q':
		fallthrough
	case 'W','X':
		fallthrough
	case 'Z','[','\\',']','^','_','`':
		fallthrough
	case 'f':
		fallthrough
	case 'q':
		fallthrough
	case 'w','x':
		fallthrough
	case 'z','{','|','}','~',0x7F:
		goto yy1
	case '\'':
		goto yy2
	case 'A':
		fallthrough
	case 'a':
		goto yy4
	case 'B':
		fallthrough
	case 'b':
		goto yy5
	case 'C':
		fallthrough
	case 'c':
		goto yy7
	case 'D':
		fallthrough
	case 'd':
		goto yy9
	case 'E':
		fallthrough
	case 'e':
		goto yy11
	case 'G':
		fallthrough
	case 'g':
		goto yy12
	case 'H':
		goto yy14
	case 'I':
		fallthrough
	case 'i':
		goto yy16
	case 'J':
		fallthrough
	case 'j':
		goto yy17
	case 'K':
		fallthrough
	case 'k':
		goto yy19
	case 'L':
		fallthrough
	case 'l':
		goto yy21
	case 'M':
		fallthrough
	case 'm':
		goto yy23
	case 'N':
		fallthrough
	case 'n':
		goto yy25
	case 'O':
		fallthrough
	case 'o':
		goto yy26
	case 'P':
		fallthrough
	case 'p':
		goto yy27
	case 'R':
		fallthrough
	case 'r':
		goto yy29
	case 'S':
		fallthrough
	case 's':
		goto yy31
	case 'T':
		fallthrough
	case 't':
		goto yy32
	case 'U':
		fallthrough
	case 'u':
		goto yy34
	case 'V':
		fallthrough
	case 'v':
		goto yy35
	case 'Y':
		fallthrough
	case 'y':
		goto yy36
	case 'h':
		goto yy37
	case 0xC2:
		fallthrough
	case 0xC7,0xC8:
		fallthrough
	case 0xCA,0xCB,0xCC,0xCD,0xCE,0xCF,0xD0,0xD1,0xD2:
		fallthrough
	case 0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF:
		goto yy40
	case 0xC3:
		goto yy41
	case 0xC4:
		goto yy42
	case 0xC5:
		goto yy43
	case 0xC6:
		goto yy44
	case 0xC9:
		goto yy45
	case 0xD3:
		goto yy46
	case 0xE0:
		goto yy47
	case 0xE1:
		goto yy48
	case 0xE2:
		goto yy49
	case 0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xEB,0xEC,0xED,0xEE,0xEF:
		goto yy50
	case 0xF0:
		goto yy51
	case 0xF1,0xF2,0xF3:
		goto yy52
	case 0xF4:
		goto yy53
	default:
		goto yy38
	}
yy1:
	cursor++
//line "search/normalize.re.go":203
	{
		r, _ := utf8.DecodeRuneInString(text[:cursor])
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			return cursor, Pnul, true
		}
		return cursor, Pother, false
	}
//line "<stdout>":285
yy2:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case '!':
		goto yy54
	default:
		goto yy3
	}
yy3:
//line "search/normalize.re.go":147
	{ return cursor, Pa, false }
//line "<stdout>":298
yy4:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'I':
		fallthrough
	case 'i':
		goto yy55
	case 'U':
		fallthrough
	case 'u':
		goto yy56
	default:
		goto yy3
	}
yy5:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy57
	default:
		goto yy6
	}
yy6:
//line "search/normalize.re.go":187
	{ return cursor, Pb, false }
//line "<stdout>":328
yy7:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy58
	default:
		goto yy8
	}
yy8:
//line "search/normalize.re.go":170
	{ return cursor, Pc, false }
//line "<stdout>":343
yy9:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy59
	default:
		goto yy10
	}
yy10:
//line "search/normalize.re.go":182
	{ return cursor, Pd, false }
//line "<stdout>":358
yy11:
	cursor++
//line "search/normalize.re.go":157
	{ return cursor, Pe, false }
//line "<stdout>":363
yy12:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy60
	default:
		goto yy13
	}
yy13:
//line "search/normalize.re.go":167
	{ return cursor, Pg, false }
//line "<stdout>":378
yy14:
	yyaccept = 0
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy61
	default:
		goto yy15
	}
yy15:
//line "search/normalize.re.go":197
	{ return cursor, Ph, false }
//line "<stdout>":393
yy16:
	cursor++
//line "search/normalize.re.go":149
	{ return cursor, Pi, false }
//line "<stdout>":398
yy17:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy63
	default:
		goto yy18
	}
yy18:
//line "search/normalize.re.go":172
	{ return cursor, Pj, false }
//line "<stdout>":413
yy19:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy64
	default:
		goto yy20
	}
yy20:
//line "search/normalize.re.go":165
	{ return cursor, Pk, false }
//line "<stdout>":428
yy21:
	yyaccept = 1
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy65
	default:
		goto yy22
	}
yy22:
//line "search/normalize.re.go":192
	{ return cursor, Pl, false }
//line "<stdout>":443
yy23:
	yyaccept = 2
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy66
	default:
		goto yy24
	}
yy24:
//line "search/normalize.re.go":189
	{ return cursor, Pm, false }
//line "<stdout>":458
yy25:
	cursor++
//line "search/normalize.re.go":184
	{ return cursor, Pn, false }
//line "<stdout>":463
yy26:
	cursor++
//line "search/normalize.re.go":159
	{ return cursor, Po, false }
//line "<stdout>":468
yy27:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy67
	default:
		goto yy28
	}
yy28:
//line "search/normalize.re.go":185
	{ return cursor, Pp, false }
//line "<stdout>":483
yy29:
	yyaccept = 3
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy68
	default:
		goto yy30
	}
yy30:
//line "search/normalize.re.go":191
	{ return cursor, Pr, false }
//line "<stdout>":498
yy31:
	cursor++
//line "search/normalize.re.go":196
	{ return cursor, Ps, false }
//line "<stdout>":503
yy32:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy69
	default:
		goto yy33
	}
yy33:
//line "search/normalize.re.go":180
	{ return cursor, Pt, false }
//line "<stdout>":518
yy34:
	cursor++
//line "search/normalize.re.go":151
	{ return cursor, Pu, false }
//line "<stdout>":523
yy35:
	cursor++
//line "search/normalize.re.go":193
	{ return cursor, Pv, false }
//line "<stdout>":528
yy36:
	cursor++
//line "search/normalize.re.go":190
	{ return cursor, Py, false }
//line "<stdout>":533
yy37:
	cursor++
	goto yy15
yy38:
	cursor++
yy39:
//line "search/normalize.re.go":130
	{ return 1, Pnul, true }
//line "<stdout>":542
yy40:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	default:
		goto yy39
	}
yy41:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90:
		fallthrough
	case 0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0:
		fallthrough
	case 0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x91:
		fallthrough
	case 0xB1:
		goto yy70
	default:
		goto yy39
	}
yy42:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81:
		goto yy71
	case 0x82,0x83:
		goto yy54
	case 0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93:
		fallthrough
	case 0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9:
		fallthrough
	case 0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x94,0x95:
		goto yy11
	case 0xAA,0xAB:
		goto yy72
	case 0xAC,0xAD:
		goto yy16
	default:
		goto yy39
	}
yy43:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D:
		fallthrough
	case 0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99:
		fallthrough
	case 0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9:
		fallthrough
	case 0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x8E,0x8F:
		goto yy26
	case 0x9A,0x9B:
		goto yy73
	case 0xAA,0xAB:
		goto yy74
	case 0xAC,0xAD:
		goto yy34
	default:
		goto yy39
	}
yy44:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E:
		fallthrough
	case 0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x8F:
		goto yy75
	default:
		goto yy39
	}
yy45:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98:
		fallthrough
	case 0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x99:
		goto yy75
	default:
		goto yy39
	}
yy46:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97:
		fallthrough
	case 0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x98,0x99:
		goto yy75
	default:
		goto yy39
	}
yy47:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy77
	default:
		goto yy39
	}
yy48:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7:
		fallthrough
	case 0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy77
	case 0xB8:
		goto yy78
	case 0xB9:
		goto yy79
	case 0xBA:
		goto yy80
	default:
		goto yy39
	}
yy49:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80:
		goto yy81
	case 0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy77
	default:
		goto yy39
	}
yy50:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy77
	default:
		goto yy39
	}
yy51:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy82
	default:
		goto yy39
	}
yy52:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy82
	default:
		goto yy39
	}
yy53:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F:
		goto yy82
	default:
		goto yy39
	}
yy54:
	cursor++
	goto yy3
yy55:
	cursor++
//line "search/normalize.re.go":158
	{ return cursor, Pai, false }
//line "<stdout>":748
yy56:
	cursor++
//line "search/normalize.re.go":160
	{ return cursor, Pau, false }
//line "<stdout>":753
yy57:
	cursor++
//line "search/normalize.re.go":188
	{ return cursor, Pbh, false }
//line "<stdout>":758
yy58:
	cursor++
//line "search/normalize.re.go":171
	{ return cursor, Pch, false }
//line "<stdout>":763
yy59:
	cursor++
//line "search/normalize.re.go":183
	{ return cursor, Pdh, false }
//line "<stdout>":768
yy60:
	cursor++
//line "search/normalize.re.go":168
	{ return cursor, Pgh, false }
//line "<stdout>":773
yy61:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xB1:
		goto yy83
	default:
		goto yy62
	}
yy62:
	cursor = marker
	switch (yyaccept) {
	case 0:
		goto yy15
	case 1:
		goto yy22
	case 2:
		goto yy24
	case 3:
		goto yy30
	case 4:
		goto yy39
	case 5:
		goto yy76
	case 6:
		goto yy85
	default:
		goto yy88
	}
yy63:
	cursor++
//line "search/normalize.re.go":173
	{ return cursor, Pjh, false }
//line "<stdout>":807
yy64:
	cursor++
//line "search/normalize.re.go":166
	{ return cursor, Pkh, false }
//line "<stdout>":812
yy65:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA5:
		goto yy84
	default:
		goto yy62
	}
yy66:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x83:
		fallthrough
	case 0x90:
		goto yy86
	default:
		goto yy62
	}
yy67:
	cursor++
//line "search/normalize.re.go":186
	{ return cursor, Pph, false }
//line "<stdout>":837
yy68:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA5:
		goto yy87
	default:
		goto yy62
	}
yy69:
	cursor++
//line "search/normalize.re.go":181
	{ return cursor, Pth, false }
//line "<stdout>":851
yy70:
	cursor++
//line "search/normalize.re.go":174
	{ return cursor, Pñ, false }
//line "<stdout>":856
yy71:
	cursor++
//line "search/normalize.re.go":148
	{ return cursor, Pā, false }
//line "<stdout>":861
yy72:
	cursor++
//line "search/normalize.re.go":150
	{ return cursor, Pī, false }
//line "<stdout>":866
yy73:
	cursor++
//line "search/normalize.re.go":194
	{ return cursor, Pś, false }
//line "<stdout>":871
yy74:
	cursor++
//line "search/normalize.re.go":152
	{ return cursor, Pū, false }
//line "<stdout>":876
yy75:
	yyaccept = 5
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy89
	default:
		goto yy76
	}
yy76:
//line "search/normalize.re.go":201
	{ return cursor, Pschwa, false }
//line "<stdout>":891
yy77:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	default:
		goto yy62
	}
yy78:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B:
		fallthrough
	case 0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3:
		fallthrough
	case 0xA6,0xA7,0xA8,0xA9:
		fallthrough
	case 0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5:
		fallthrough
	case 0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x8C,0x8D:
		goto yy90
	case 0xA4,0xA5:
		fallthrough
	case 0xAA,0xAB:
		goto yy83
	case 0xB6,0xB7:
		goto yy92
	case 0xB8,0xB9:
		goto yy93
	default:
		goto yy62
	}
yy79:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83:
		goto yy86
	case 0x84,0x85:
		goto yy94
	case 0x86,0x87:
		goto yy95
	case 0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99:
		fallthrough
	case 0x9E,0x9F,0xA0,0xA1:
		fallthrough
	case 0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB:
		fallthrough
	case 0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x9A,0x9B:
		goto yy96
	case 0x9C,0x9D:
		goto yy97
	case 0xA2,0xA3:
		goto yy98
	case 0xAC,0xAD:
		goto yy99
	default:
		goto yy62
	}
yy80:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95:
		fallthrough
	case 0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x96:
		goto yy83
	default:
		goto yy62
	}
yy81:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98:
		fallthrough
	case 0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x99:
		goto yy2
	default:
		goto yy62
	}
yy82:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy77
	default:
		goto yy62
	}
yy83:
	cursor++
//line "search/normalize.re.go":164
	{ return cursor, Pḥ, false }
//line "<stdout>":996
yy84:
	yyaccept = 6
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy101
	default:
		goto yy85
	}
yy85:
//line "search/normalize.re.go":155
	{ return cursor, Pḷ, false }
//line "<stdout>":1011
yy86:
	cursor++
//line "search/normalize.re.go":162
	{ return cursor, Pṃ, false }
//line "<stdout>":1016
yy87:
	yyaccept = 7
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy102
	default:
		goto yy88
	}
yy88:
//line "search/normalize.re.go":153
	{ return cursor, Pṛ, false }
//line "<stdout>":1031
yy89:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy103
	default:
		goto yy62
	}
yy90:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy104
	default:
		goto yy91
	}
yy91:
//line "search/normalize.re.go":177
	{ return cursor, Pḍ, false }
//line "<stdout>":1055
yy92:
	cursor++
	goto yy85
yy93:
	cursor++
//line "search/normalize.re.go":156
	{ return cursor, Pḹ, false }
//line "<stdout>":1063
yy94:
	cursor++
//line "search/normalize.re.go":169
	{ return cursor, Pṅ, false }
//line "<stdout>":1068
yy95:
	cursor++
//line "search/normalize.re.go":179
	{ return cursor, Pṇ, false }
//line "<stdout>":1073
yy96:
	cursor++
	goto yy88
yy97:
	cursor++
//line "search/normalize.re.go":154
	{ return cursor, Pṝ, false }
//line "<stdout>":1081
yy98:
	cursor++
//line "search/normalize.re.go":195
	{ return cursor, Pṣ, false }
//line "<stdout>":1086
yy99:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy105
	default:
		goto yy100
	}
yy100:
//line "search/normalize.re.go":175
	{ return cursor, Pṭ, false }
//line "<stdout>":1101
yy101:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy93
	default:
		goto yy62
	}
yy102:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy97
	default:
		goto yy62
	}
yy103:
	cursor++
//line "search/normalize.re.go":202
	{ return cursor, Plongschwa, false }
//line "<stdout>":1124
yy104:
	cursor++
//line "search/normalize.re.go":178
	{ return cursor, Pḍh, false }
//line "<stdout>":1129
yy105:
	cursor++
//line "search/normalize.re.go":176
	{ return cursor, Pṭh, false }
//line "<stdout>":1134
}
//line "search/normalize.re.go":210

	return 0, 0, false
}

// consumeToken reads the next token and aligns the cursor with grapheme boundaries.
// It absorbs any trailing combining characters attached to the recognized sequence.
func consumeToken(text string) (int, int, bool) {
	matchLen, rep, elide := lexPrefix(text)
	consumed := 0
	state := -1
	rest := text
	for consumed < matchLen {
		var cluster string
		cluster, rest, _, state = uniseg.StepString(rest, state)
		consumed += len(cluster)
	}
	return consumed, rep, elide
}

// lexReduced applies phonological transformations on the binary representation.
// It maps encoded sequences to a further reduced structural logic.
func lexReduced(encoded string) (int, int) {
	cursor, marker := 0, 0
	_ = cursor
	_ = marker
	
//line "<stdout>":1163
{
	var yych byte
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case 0x00:
		goto yy107
	case 0x01,0x02:
		goto yy108
	case 0x03,0x04:
		goto yy109
	case 0x05,0x06:
		goto yy110
	case 0x07,0x08:
		goto yy111
	case '\t','\n':
		goto yy112
	case '\v':
		goto yy113
	case '\f':
		goto yy114
	case '\r':
		goto yy115
	case 0x0E:
		goto yy116
	case 0x0F:
		goto yy117
	case 0x10:
		fallthrough
	case '1':
		goto yy119
	case 0x11:
		goto yy120
	case 0x12:
		fallthrough
	case 0x14:
		goto yy122
	case 0x13:
		goto yy123
	case 0x15:
		goto yy124
	case 0x16:
		goto yy125
	case 0x17:
		fallthrough
	case 0x19:
		goto yy127
	case 0x18:
		goto yy128
	case 0x1A:
		goto yy129
	case 0x1B:
		goto yy130
	case 0x1C:
		fallthrough
	case 0x1E:
		fallthrough
	case '!':
		fallthrough
	case '#':
		goto yy132
	case 0x1D:
		goto yy133
	case 0x1F:
		goto yy134
	case ' ':
		goto yy135
	case '"':
		goto yy136
	case '$':
		goto yy137
	case '%':
		goto yy138
	case '&':
		fallthrough
	case '(':
		goto yy140
	case '\'':
		goto yy141
	case ')':
		goto yy142
	case '*':
		goto yy143
	case '+':
		goto yy145
	case ',':
		goto yy147
	case '-':
		goto yy149
	case '.','/','0':
		goto yy151
	case '2','3':
		goto yy152
	case '4':
		goto yy153
	default:
		goto yy154
	}
yy107:
	cursor++
//line "search/normalize.re.go":244
	{ return 1, Pnul }
//line "<stdout>":1265
yy108:
	cursor++
//line "search/normalize.re.go":300
	{ return cursor, Pa }
//line "<stdout>":1270
yy109:
	cursor++
//line "search/normalize.re.go":301
	{ return cursor, Pi }
//line "<stdout>":1275
yy110:
	cursor++
//line "search/normalize.re.go":302
	{ return cursor, Pu }
//line "<stdout>":1280
yy111:
	cursor++
//line "search/normalize.re.go":303
	{ return cursor, Pṛ }
//line "<stdout>":1285
yy112:
	cursor++
//line "search/normalize.re.go":304
	{ return cursor, Pḷ }
//line "<stdout>":1290
yy113:
	cursor++
//line "search/normalize.re.go":305
	{ return cursor, Pe }
//line "<stdout>":1295
yy114:
	cursor++
//line "search/normalize.re.go":306
	{ return cursor, Pai }
//line "<stdout>":1300
yy115:
	cursor++
//line "search/normalize.re.go":307
	{ return cursor, Po }
//line "<stdout>":1305
yy116:
	cursor++
//line "search/normalize.re.go":308
	{ return cursor, Pau }
//line "<stdout>":1310
yy117:
	cursor++
yy118:
//line "search/normalize.re.go":311
	{ return cursor, Pn }
//line "<stdout>":1316
yy119:
	cursor++
//line "search/normalize.re.go":309
	{ return cursor, Ph }
//line "<stdout>":1321
yy120:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case 0x11,0x12:
		goto yy122
	default:
		goto yy121
	}
yy121:
//line "search/normalize.re.go":310
	{ return cursor, Pk }
//line "<stdout>":1334
yy122:
	cursor++
	goto yy121
yy123:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case 0x13,0x14:
		goto yy122
	default:
		goto yy121
	}
yy124:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case 0x15:
		goto yy117
	default:
		goto yy118
	}
yy125:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case 0x16,0x17:
		goto yy127
	default:
		goto yy126
	}
yy126:
//line "search/normalize.re.go":312
	{ return cursor, Pc }
//line "<stdout>":1368
yy127:
	cursor++
	goto yy126
yy128:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case 0x18,0x19:
		goto yy127
	default:
		goto yy126
	}
yy129:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case 0x1A:
		goto yy117
	default:
		goto yy118
	}
yy130:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case 0x1B,0x1C:
		goto yy132
	default:
		goto yy131
	}
yy131:
//line "search/normalize.re.go":313
	{ return cursor, Pt }
//line "<stdout>":1402
yy132:
	cursor++
	goto yy131
yy133:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case 0x1D,0x1E:
		goto yy132
	default:
		goto yy131
	}
yy134:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case 0x1F:
		goto yy117
	default:
		goto yy118
	}
yy135:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case ' ','!':
		goto yy132
	default:
		goto yy131
	}
yy136:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case '"','#':
		goto yy132
	default:
		goto yy131
	}
yy137:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case '$':
		goto yy117
	default:
		goto yy118
	}
yy138:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case '%','&':
		goto yy140
	default:
		goto yy139
	}
yy139:
//line "search/normalize.re.go":314
	{ return cursor, Pp }
//line "<stdout>":1463
yy140:
	cursor++
	goto yy139
yy141:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case '\'','(':
		goto yy140
	default:
		goto yy139
	}
yy142:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case ')':
		goto yy117
	default:
		goto yy118
	}
yy143:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case '*':
		goto yy155
	default:
		goto yy144
	}
yy144:
//line "search/normalize.re.go":315
	{ return cursor, Py }
//line "<stdout>":1497
yy145:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case '+':
		goto yy156
	default:
		goto yy146
	}
yy146:
//line "search/normalize.re.go":316
	{ return cursor, Pr }
//line "<stdout>":1510
yy147:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case ',':
		goto yy157
	default:
		goto yy148
	}
yy148:
//line "search/normalize.re.go":317
	{ return cursor, Pl }
//line "<stdout>":1523
yy149:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case '-':
		goto yy158
	default:
		goto yy150
	}
yy150:
//line "search/normalize.re.go":318
	{ return cursor, Pv }
//line "<stdout>":1536
yy151:
	cursor++
//line "search/normalize.re.go":319
	{ return cursor, Ps }
//line "<stdout>":1541
yy152:
	cursor++
//line "search/normalize.re.go":320
	{ return cursor, Pschwa }
//line "<stdout>":1546
yy153:
	cursor++
//line "search/normalize.re.go":321
	{ return cursor, Pother }
//line "<stdout>":1551
yy154:
	cursor++
//line "search/normalize.re.go":323
	{ return 1, int(encoded[0]) }
//line "<stdout>":1556
yy155:
	cursor++
	goto yy144
yy156:
	cursor++
	goto yy146
yy157:
	cursor++
	goto yy148
yy158:
	cursor++
	goto yy150
}
//line "search/normalize.re.go":324

	return 0, 0
}

// encodeSequence converts UTF-8 text to the internal binary sequence without allocating bounds.
// It is optimized for high-speed evaluation during the filtering phase.
func encodeSequence(text string) string {
	var seq strings.Builder
	for len(text) > 0 {
		consumed, rep, elide := consumeToken(text)
		if elide {
			text = text[consumed:]
			continue
		}
		seq.WriteByte(byte(rep))
		text = text[consumed:]
	}
	return seq.String()
}

// encodeSequenceWithBounds converts text to the internal sequence and returns an interleaved bounds array.
// The array alternates original start and original end indices for each byte.
func encodeSequenceWithBounds(text string) (string, []int) {
	var seq strings.Builder
	var bounds []int
	cursor := 0
	for len(text) > 0 {
		consumed, rep, elide := consumeToken(text)
		if elide {
			cursor += consumed
			text = text[consumed:]
			continue
		}
		endCursor := cursor + consumed
		seq.WriteByte(byte(rep))
		bounds = append(bounds, cursor, endCursor)
		cursor = endCursor
		text = text[consumed:]
	}
	return seq.String(), bounds
}

// reduceSequence converts the encoded sequence to a reduced state without calculating positional bounds.
// It applies phonological neutralizations strictly for content matching.
func reduceSequence(encoded string) string {
	var reduced strings.Builder
	for len(encoded) > 0 {
		consumed, rep := lexReduced(encoded)
		if rep == Pnul {
			break
		}
		reduced.WriteByte(byte(rep))
		encoded = encoded[consumed:]
	}
	return reduced.String()
}

// reduceSequenceWithBounds converts the encoded sequence and maintains sequence bounds.
// It maps the reduced byte sequence back to its boundaries within the original encoded sequence.
func reduceSequenceWithBounds(encoded string) (string, []int) {
	var reduced strings.Builder
	var bounds []int
	cursor := 0
	for len(encoded) > 0 {
		consumed, rep := lexReduced(encoded)
		if rep == Pnul {
			break
		}
		reduced.WriteByte(byte(rep))
		bounds = append(bounds, cursor, cursor+consumed)
		cursor += consumed
		encoded = encoded[consumed:]
	}
	return reduced.String(), bounds
}

const normalFirst = 0xE002
const Slongschwa = string(normalFirst + Plongschwa)

var folder = cases.Fold()

// lexNormalPrefix uses a finite state machine to identify the next sequence for normal mode.
// It returns the byte length of the matched sequence, its replacement string, and an elision flag.
func lexNormalPrefix(text string) (int, string, bool) {
	cursor, marker := 0, 0
	_ = cursor
	_ = marker
	
//line "<stdout>":1659
{
	var yych byte
	yyaccept := 0
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,'\t','\n','\v','\f','\r',0x0E,0x0F,0x10,0x11,0x12,0x13,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x1C,0x1D,0x1E,0x1F,' ','!','"','#','$','%','&','\'','(',')','*','+',',','-','.','/','0','1','2','3','4','5','6','7','8','9',':',';','<','=','>','?','@','A','B','C','D','E','F','G':
		fallthrough
	case 'I','J','K':
		fallthrough
	case 'N','O','P','Q':
		fallthrough
	case 'S','T','U','V','W','X','Y','Z','[','\\',']','^','_','`','a','b','c','d','e','f','g','h','i','j','k':
		fallthrough
	case 'n','o','p','q':
		fallthrough
	case 's','t','u','v','w','x','y','z','{','|','}','~',0x7F:
		goto yy160
	case 'H':
		goto yy162
	case 'L':
		fallthrough
	case 'l':
		goto yy163
	case 'M':
		fallthrough
	case 'm':
		goto yy164
	case 'R':
		fallthrough
	case 'r':
		goto yy165
	case 0xC2:
		fallthrough
	case 0xC7,0xC8:
		fallthrough
	case 0xCA,0xCB,0xCC,0xCD,0xCE,0xCF,0xD0,0xD1,0xD2:
		fallthrough
	case 0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF:
		goto yy168
	case 0xC3:
		goto yy169
	case 0xC4:
		goto yy170
	case 0xC5:
		goto yy171
	case 0xC6:
		goto yy172
	case 0xC9:
		goto yy173
	case 0xD3:
		goto yy174
	case 0xE0:
		goto yy175
	case 0xE1:
		goto yy176
	case 0xE2,0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xEB,0xEC,0xED,0xEE,0xEF:
		goto yy177
	case 0xF0:
		goto yy178
	case 0xF1,0xF2,0xF3:
		goto yy179
	case 0xF4:
		goto yy180
	default:
		goto yy166
	}
yy160:
	cursor++
yy161:
//line "search/normalize.re.go":437
	{
		r, size := utf8.DecodeRuneInString(text)
		return size, folder.String(string(r)), false
	}
//line "<stdout>":1734
yy162:
	yyaccept = 0
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy181
	default:
		goto yy161
	}
yy163:
	yyaccept = 0
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy183
	default:
		goto yy161
	}
yy164:
	yyaccept = 0
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy184
	default:
		goto yy161
	}
yy165:
	yyaccept = 0
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy185
	default:
		goto yy161
	}
yy166:
	cursor++
yy167:
//line "search/normalize.re.go":419
	{ return 1, "", true }
//line "<stdout>":1784
yy168:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy160
	default:
		goto yy167
	}
yy169:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85:
		fallthrough
	case 0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5:
		fallthrough
	case 0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy160
	case 0x86:
		fallthrough
	case 0xA6:
		goto yy186
	default:
		goto yy167
	}
yy170:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81:
		fallthrough
	case 0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F:
		fallthrough
	case 0x92,0x93:
		fallthrough
	case 0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB:
		fallthrough
	case 0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy160
	case 0x82,0x83:
		goto yy187
	case 0x90,0x91:
		goto yy188
	case 0x94,0x95:
		goto yy189
	case 0xAC,0xAD:
		goto yy190
	default:
		goto yy167
	}
yy171:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D:
		fallthrough
	case 0x90,0x91:
		fallthrough
	case 0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB:
		fallthrough
	case 0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy160
	case 0x8E,0x8F:
		goto yy191
	case 0x92,0x93:
		goto yy192
	case 0xAC,0xAD:
		goto yy193
	default:
		goto yy167
	}
yy172:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E:
		fallthrough
	case 0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy160
	case 0x8F:
		goto yy194
	default:
		goto yy167
	}
yy173:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98:
		fallthrough
	case 0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy160
	case 0x99:
		goto yy194
	default:
		goto yy167
	}
yy174:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97:
		fallthrough
	case 0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy160
	case 0x98,0x99:
		goto yy195
	default:
		goto yy167
	}
yy175:
	yyaccept = 1
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy197
	default:
		goto yy167
	}
yy176:
	yyaccept = 1
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7:
		fallthrough
	case 0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy197
	case 0xB8:
		goto yy198
	case 0xB9:
		goto yy199
	case 0xBA:
		goto yy200
	default:
		goto yy167
	}
yy177:
	yyaccept = 1
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy197
	default:
		goto yy167
	}
yy178:
	yyaccept = 1
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy201
	default:
		goto yy167
	}
yy179:
	yyaccept = 1
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy201
	default:
		goto yy167
	}
yy180:
	yyaccept = 1
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F:
		goto yy201
	default:
		goto yy167
	}
yy181:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xB1:
		goto yy202
	default:
		goto yy182
	}
yy182:
	cursor = marker
	switch (yyaccept) {
	case 0:
		goto yy161
	case 1:
		goto yy167
	case 2:
		goto yy196
	case 3:
		goto yy204
	default:
		goto yy207
	}
yy183:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA5:
		goto yy203
	default:
		goto yy182
	}
yy184:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x83:
		fallthrough
	case 0x90:
		goto yy205
	default:
		goto yy182
	}
yy185:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA5:
		goto yy206
	default:
		goto yy182
	}
yy186:
	cursor++
//line "search/normalize.re.go":425
	{ return cursor, "ae", false }
//line "<stdout>":2026
yy187:
	cursor++
//line "search/normalize.re.go":420
	{ return cursor, "a", false }
//line "<stdout>":2031
yy188:
	cursor++
//line "search/normalize.re.go":427
	{ return cursor, "d", false }
//line "<stdout>":2036
yy189:
	cursor++
//line "search/normalize.re.go":421
	{ return cursor, "e", false }
//line "<stdout>":2041
yy190:
	cursor++
//line "search/normalize.re.go":422
	{ return cursor, "i", false }
//line "<stdout>":2046
yy191:
	cursor++
//line "search/normalize.re.go":423
	{ return cursor, "o", false }
//line "<stdout>":2051
yy192:
	cursor++
//line "search/normalize.re.go":426
	{ return cursor, "oe", false }
//line "<stdout>":2056
yy193:
	cursor++
//line "search/normalize.re.go":424
	{ return cursor, "u", false }
//line "<stdout>":2061
yy194:
	yyaccept = 0
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy208
	default:
		goto yy161
	}
yy195:
	yyaccept = 2
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy208
	default:
		goto yy196
	}
yy196:
//line "search/normalize.re.go":432
	{ return cursor, "ə", false }
//line "<stdout>":2087
yy197:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy160
	default:
		goto yy182
	}
yy198:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3:
		fallthrough
	case 0xA6,0xA7,0xA8,0xA9:
		fallthrough
	case 0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy160
	case 0xA4,0xA5:
		fallthrough
	case 0xAA,0xAB:
		goto yy202
	default:
		goto yy182
	}
yy199:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83:
		goto yy205
	case 0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy160
	default:
		goto yy182
	}
yy200:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95:
		fallthrough
	case 0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy160
	case 0x96:
		goto yy202
	default:
		goto yy182
	}
yy201:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy197
	default:
		goto yy182
	}
yy202:
	cursor++
//line "search/normalize.re.go":435
	{ return cursor, "ḥ", false }
//line "<stdout>":2151
yy203:
	yyaccept = 3
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy209
	default:
		goto yy204
	}
yy204:
//line "search/normalize.re.go":430
	{ return cursor, "ḷ", false }
//line "<stdout>":2166
yy205:
	cursor++
//line "search/normalize.re.go":434
	{ return cursor, "ṃ", false }
//line "<stdout>":2171
yy206:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy210
	default:
		goto yy207
	}
yy207:
//line "search/normalize.re.go":428
	{ return cursor, "ṛ", false }
//line "<stdout>":2186
yy208:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy211
	default:
		goto yy182
	}
yy209:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy212
	default:
		goto yy182
	}
yy210:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy213
	default:
		goto yy182
	}
yy211:
	cursor++
//line "search/normalize.re.go":433
	{ return cursor, Slongschwa, false }
//line "<stdout>":2218
yy212:
	cursor++
//line "search/normalize.re.go":431
	{ return cursor, "ḹ", false }
//line "<stdout>":2223
yy213:
	cursor++
//line "search/normalize.re.go":429
	{ return cursor, "ṹ", false }
//line "<stdout>":2228
}
//line "search/normalize.re.go":441

	return 0, "", false
}

// consumeNormalToken reads the next token and aligns with grapheme boundaries.
// It discards trailing combining characters to keep only the base normalization.
// Note: this logic incorrectly handles Unicode Regional Indicator sequences.
// Because emoji flags are formed by pairs of Regional Indicators within a single
// grapheme cluster, the second indicator is deliberately but erroneously stripped.
func consumeNormalToken(text string) (int, string, bool) {
	matchLen, rep, elide := lexNormalPrefix(text)
	consumed := 0
	state := -1
	rest := text
	for consumed < matchLen {
		var cluster string
		cluster, rest, _, state = uniseg.StepString(rest, state)
		consumed += len(cluster)
	}
	return consumed, rep, elide
}

// transformNormal applies transformations for normal matching without allocating memory bounds.
// This fast path is crucial for eliminating garbage collection overhead during filtering.
func transformNormal(text string) string {
	var folded strings.Builder
	for len(text) > 0 {
		consumed, rep, elide := consumeNormalToken(text)
		if elide {
			text = text[consumed:]
			continue
		}
		folded.WriteString(rep)
		text = text[consumed:]
	}
	return folded.String()
}

// transformNormalWithBounds applies transformations and records interleaved index bounds.
// The returned array stores the exact original start and end byte offsets.
func transformNormalWithBounds(text string) (string, []int) {
	var folded strings.Builder
	var bounds []int
	cursor := 0
	for len(text) > 0 {
		consumed, rep, elide := consumeNormalToken(text)
		if elide {
			cursor += consumed
			text = text[consumed:]
			continue
		}
		endCursor := cursor + consumed
		n := len(rep)
		for j := 0; j < n; j++ {
			bounds = append(bounds, cursor, endCursor)
		}
		folded.WriteString(rep)
		cursor = endCursor
		text = text[consumed:]
	}
	return folded.String(), bounds
}

// transformNormalized executes the complete formb pipeline purely for content evaluation.
// It bypasses the generation of transitive index bounds to conserve memory.
func transformNormalized(text string) string {
	return reduceSequence(encodeSequence(text))
}

// transformNormalizedWithBounds tracks structural limits across the double normalization.
// It recursively retrieves the initial offsets using the boundaries of the reduced sequence.
func transformNormalizedWithBounds(text string) (string, []int) {
	seq, boundsA := encodeSequenceWithBounds(text)
	reduced, boundsB := reduceSequenceWithBounds(seq)
	var finalBounds []int
	for i := 0; i < len(reduced); i++ {
		startA := boundsB[2*i]
		endA := boundsB[2*i+1] - 1
		finalBounds = append(finalBounds, boundsA[2*startA], boundsA[2*endA+1])
	}
	return reduced, finalBounds
}

// transform acts as a fast text dispatcher ignoring positional metadata.
// It is intended for boolean evaluation matrices.
func transform(text string, mode string) string {
	if mode == "formb" {
		return transformNormalized(text)
	}
	return transformNormal(text)
}

// transformWithBounds computes structural offsets alongside textual mapping.
// It is strictly reserved for the final highlight processing layer.
func transformWithBounds(text string, mode string) (string, []int) {
	if mode == "formb" {
		return transformNormalizedWithBounds(text)
	}
	return transformNormalWithBounds(text)
}
