// Code generated by re2c 3.1 on Wed Jun 24 15:53:37 2026, DO NOT EDIT.
//line "search/normalize.re.go":1


package main

import (
	"log"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/rivo/uniseg"
	"golang.org/x/text/cases"
)

// Dummy variables to prevent IDE formatters from stripping required imports.
var (
	_ = utf8.DecodeRuneInString
	_ = unicode.IsLetter
	_ = log.Fatalf
	_ = cases.Fold
)

const (
	Pnul = iota
	Pa
	Pā
	Pi
	Pī
	Pu
	Pū
	Pṛ
	Pṝ
	Pḷ
	Pḹ
	Pe
	Pai
	Po
	Pau
	Pṃ
	Pḥ
	Pk
	Pkh
	Pg
	Pgh
	Pṅ
	Pc
	Pch
	Pj
	Pjh
	Pñ
	Pṭ
	Pṭh
	Pḍ
	Pḍh
	Pṇ
	Pt
	Pth
	Pd
	Pdh
	Pn
	Pp
	Pph
	Pb
	Pbh
	Pm
	Py
	Pr
	Pl
	Pv
	Pś
	Pṣ
	Ps
	Ph
	Pschwa
	Plongschwa
	P0
	P1
	P2
	P3
	P4
	P5
	P6
	P7
	P8
	P9
	Pother
)

var phonemeLookup = []string{
	"!",
	"a", "ā", "i", "ī", "u", "ū",
	"ṛ", "ṝ", "ḷ", "ḹ",
	"e", "ai", "o", "au",
	"ṃ", "ḥ",
	"k", "kh", "g", "gh", "ṅ",
	"c", "ch", "j", "jh", "ñ",
	"ṭ", "ṭh", "ḍ", "ḍh", "ṇ",
	"t", "th", "d", "dh", "n",
	"p", "ph", "b", "bh", "m",
	"y", "r", "l", "v",
	"ś", "ṣ", "s", "h",
	"ə", "ə̄",
	"0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
	"?",
}

// peekByte safely reads a byte from a string to prevent out-of-bounds panics in re2c.
// It returns 0 when the cursor reaches or exceeds the string length.
func peekByte(s string, i int) byte {
	if i < len(s) {
		return s[i]
	}
	return 0
}

// makePrintable converts the internal binary representation back to readable characters.
// It maps sequence codes to their IAST equivalents for debugging purposes.
func makePrintable(s string) string {
	var buf strings.Builder
	for i := 0; i < len(s); i++ {
		c := int(s[i])
		buf.WriteString(phonemeLookup[c])
	}
	return buf.String()
}

// lexPrefix uses a finite state machine to identify the next semantic sequence.
// It returns the byte length of the matched sequence, its replacement, and an elision flag.
func lexPrefix(text string) (int, int, bool) {
	cursor, marker := 0, 0
	_ = cursor
	_ = marker
	_ = text
	
//line "<stdout>":138
{
	var yych byte
	yyaccept := 0
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,'\t','\n','\v','\f','\r',0x0E,0x0F,0x10,0x11,0x12,0x13,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x1C,0x1D,0x1E,0x1F,' ','!','"','#','$','%','&':
		fallthrough
	case '(',')','*','+',',','-','.','/':
		fallthrough
	case ':',';','<','=','>','?','@':
		fallthrough
	case 'F':
		fallthrough
	case 'Q':
		fallthrough
	case 'W','X':
		fallthrough
	case 'Z','[','\\',']','^','_','`':
		fallthrough
	case 'f':
		fallthrough
	case 'q':
		fallthrough
	case 'w','x':
		fallthrough
	case 'z','{','|','}','~',0x7F:
		goto yy1
	case '\'':
		goto yy2
	case '0':
		goto yy4
	case '1':
		goto yy5
	case '2':
		goto yy6
	case '3':
		goto yy7
	case '4':
		goto yy8
	case '5':
		goto yy9
	case '6':
		goto yy10
	case '7':
		goto yy11
	case '8':
		goto yy12
	case '9':
		goto yy13
	case 'A':
		fallthrough
	case 'a':
		goto yy14
	case 'B':
		fallthrough
	case 'b':
		goto yy15
	case 'C':
		fallthrough
	case 'c':
		goto yy17
	case 'D':
		fallthrough
	case 'd':
		goto yy19
	case 'E':
		fallthrough
	case 'e':
		goto yy21
	case 'G':
		fallthrough
	case 'g':
		goto yy22
	case 'H':
		goto yy24
	case 'I':
		fallthrough
	case 'i':
		goto yy26
	case 'J':
		fallthrough
	case 'j':
		goto yy27
	case 'K':
		fallthrough
	case 'k':
		goto yy29
	case 'L':
		fallthrough
	case 'l':
		goto yy31
	case 'M':
		fallthrough
	case 'm':
		goto yy33
	case 'N':
		fallthrough
	case 'n':
		goto yy35
	case 'O':
		fallthrough
	case 'o':
		goto yy36
	case 'P':
		fallthrough
	case 'p':
		goto yy37
	case 'R':
		fallthrough
	case 'r':
		goto yy39
	case 'S':
		fallthrough
	case 's':
		goto yy41
	case 'T':
		fallthrough
	case 't':
		goto yy42
	case 'U':
		fallthrough
	case 'u':
		goto yy44
	case 'V':
		fallthrough
	case 'v':
		goto yy45
	case 'Y':
		fallthrough
	case 'y':
		goto yy46
	case 'h':
		goto yy47
	case 0xC2:
		fallthrough
	case 0xC7,0xC8:
		fallthrough
	case 0xCA,0xCB,0xCC,0xCD,0xCE,0xCF,0xD0,0xD1,0xD2:
		fallthrough
	case 0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF:
		goto yy50
	case 0xC3:
		goto yy51
	case 0xC4:
		goto yy52
	case 0xC5:
		goto yy53
	case 0xC6:
		goto yy54
	case 0xC9:
		goto yy55
	case 0xD3:
		goto yy56
	case 0xE0:
		goto yy57
	case 0xE1:
		goto yy58
	case 0xE2:
		goto yy59
	case 0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xEB,0xEC,0xED,0xEE,0xEF:
		goto yy60
	case 0xF0:
		goto yy61
	case 0xF1,0xF2,0xF3:
		goto yy62
	case 0xF4:
		goto yy63
	default:
		goto yy48
	}
yy1:
	cursor++
//line "search/normalize.re.go":225
	{
		r, _ := utf8.DecodeRuneInString(text[:cursor])
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			return cursor, Pnul, true
		}
		return cursor, Pother, false
	}
//line "<stdout>":319
yy2:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case '!':
		goto yy64
	default:
		goto yy3
	}
yy3:
//line "search/normalize.re.go":159
	{ return cursor, Pa, false }
//line "<stdout>":332
yy4:
	cursor++
//line "search/normalize.re.go":215
	{ return cursor, P0, false }
//line "<stdout>":337
yy5:
	cursor++
//line "search/normalize.re.go":216
	{ return cursor, P1, false }
//line "<stdout>":342
yy6:
	cursor++
//line "search/normalize.re.go":217
	{ return cursor, P2, false }
//line "<stdout>":347
yy7:
	cursor++
//line "search/normalize.re.go":218
	{ return cursor, P3, false }
//line "<stdout>":352
yy8:
	cursor++
//line "search/normalize.re.go":219
	{ return cursor, P4, false }
//line "<stdout>":357
yy9:
	cursor++
//line "search/normalize.re.go":220
	{ return cursor, P5, false }
//line "<stdout>":362
yy10:
	cursor++
//line "search/normalize.re.go":221
	{ return cursor, P6, false }
//line "<stdout>":367
yy11:
	cursor++
//line "search/normalize.re.go":222
	{ return cursor, P7, false }
//line "<stdout>":372
yy12:
	cursor++
//line "search/normalize.re.go":223
	{ return cursor, P8, false }
//line "<stdout>":377
yy13:
	cursor++
//line "search/normalize.re.go":224
	{ return cursor, P9, false }
//line "<stdout>":382
yy14:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'I':
		fallthrough
	case 'i':
		goto yy65
	case 'U':
		fallthrough
	case 'u':
		goto yy66
	default:
		goto yy3
	}
yy15:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy67
	default:
		goto yy16
	}
yy16:
//line "search/normalize.re.go":199
	{ return cursor, Pb, false }
//line "<stdout>":412
yy17:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy68
	default:
		goto yy18
	}
yy18:
//line "search/normalize.re.go":182
	{ return cursor, Pc, false }
//line "<stdout>":427
yy19:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy69
	default:
		goto yy20
	}
yy20:
//line "search/normalize.re.go":194
	{ return cursor, Pd, false }
//line "<stdout>":442
yy21:
	cursor++
//line "search/normalize.re.go":169
	{ return cursor, Pe, false }
//line "<stdout>":447
yy22:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy70
	default:
		goto yy23
	}
yy23:
//line "search/normalize.re.go":179
	{ return cursor, Pg, false }
//line "<stdout>":462
yy24:
	yyaccept = 0
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy71
	default:
		goto yy25
	}
yy25:
//line "search/normalize.re.go":209
	{ return cursor, Ph, false }
//line "<stdout>":477
yy26:
	cursor++
//line "search/normalize.re.go":161
	{ return cursor, Pi, false }
//line "<stdout>":482
yy27:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy73
	default:
		goto yy28
	}
yy28:
//line "search/normalize.re.go":184
	{ return cursor, Pj, false }
//line "<stdout>":497
yy29:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy74
	default:
		goto yy30
	}
yy30:
//line "search/normalize.re.go":177
	{ return cursor, Pk, false }
//line "<stdout>":512
yy31:
	yyaccept = 1
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy75
	default:
		goto yy32
	}
yy32:
//line "search/normalize.re.go":204
	{ return cursor, Pl, false }
//line "<stdout>":527
yy33:
	yyaccept = 2
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy76
	default:
		goto yy34
	}
yy34:
//line "search/normalize.re.go":201
	{ return cursor, Pm, false }
//line "<stdout>":542
yy35:
	cursor++
//line "search/normalize.re.go":196
	{ return cursor, Pn, false }
//line "<stdout>":547
yy36:
	cursor++
//line "search/normalize.re.go":171
	{ return cursor, Po, false }
//line "<stdout>":552
yy37:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy77
	default:
		goto yy38
	}
yy38:
//line "search/normalize.re.go":197
	{ return cursor, Pp, false }
//line "<stdout>":567
yy39:
	yyaccept = 3
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy78
	default:
		goto yy40
	}
yy40:
//line "search/normalize.re.go":203
	{ return cursor, Pr, false }
//line "<stdout>":582
yy41:
	cursor++
//line "search/normalize.re.go":208
	{ return cursor, Ps, false }
//line "<stdout>":587
yy42:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy79
	default:
		goto yy43
	}
yy43:
//line "search/normalize.re.go":192
	{ return cursor, Pt, false }
//line "<stdout>":602
yy44:
	cursor++
//line "search/normalize.re.go":163
	{ return cursor, Pu, false }
//line "<stdout>":607
yy45:
	cursor++
//line "search/normalize.re.go":205
	{ return cursor, Pv, false }
//line "<stdout>":612
yy46:
	cursor++
//line "search/normalize.re.go":202
	{ return cursor, Py, false }
//line "<stdout>":617
yy47:
	cursor++
	goto yy25
yy48:
	cursor++
yy49:
//line "search/normalize.re.go":142
	{ return 1, Pnul, true }
//line "<stdout>":626
yy50:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	default:
		goto yy49
	}
yy51:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90:
		fallthrough
	case 0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0:
		fallthrough
	case 0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x91:
		fallthrough
	case 0xB1:
		goto yy80
	default:
		goto yy49
	}
yy52:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81:
		goto yy81
	case 0x82,0x83:
		goto yy64
	case 0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91:
		fallthrough
	case 0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9:
		fallthrough
	case 0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x92,0x93,0x94,0x95:
		goto yy21
	case 0xAA,0xAB:
		goto yy82
	case 0xAC,0xAD:
		goto yy26
	default:
		goto yy49
	}
yy53:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B:
		fallthrough
	case 0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99:
		fallthrough
	case 0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9:
		fallthrough
	case 0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x8C,0x8D,0x8E,0x8F:
		goto yy36
	case 0x9A,0x9B:
		goto yy83
	case 0xAA,0xAB:
		goto yy84
	case 0xAC,0xAD:
		goto yy44
	default:
		goto yy49
	}
yy54:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E:
		fallthrough
	case 0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x8F:
		goto yy85
	default:
		goto yy49
	}
yy55:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98:
		fallthrough
	case 0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x99:
		goto yy85
	default:
		goto yy49
	}
yy56:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97:
		fallthrough
	case 0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x98,0x99:
		goto yy85
	default:
		goto yy49
	}
yy57:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy87
	default:
		goto yy49
	}
yy58:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7:
		fallthrough
	case 0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy87
	case 0xB8:
		goto yy88
	case 0xB9:
		goto yy89
	case 0xBA:
		goto yy90
	default:
		goto yy49
	}
yy59:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80:
		goto yy91
	case 0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy87
	default:
		goto yy49
	}
yy60:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy87
	default:
		goto yy49
	}
yy61:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy92
	default:
		goto yy49
	}
yy62:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy92
	default:
		goto yy49
	}
yy63:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F:
		goto yy92
	default:
		goto yy49
	}
yy64:
	cursor++
	goto yy3
yy65:
	cursor++
//line "search/normalize.re.go":170
	{ return cursor, Pai, false }
//line "<stdout>":832
yy66:
	cursor++
//line "search/normalize.re.go":172
	{ return cursor, Pau, false }
//line "<stdout>":837
yy67:
	cursor++
//line "search/normalize.re.go":200
	{ return cursor, Pbh, false }
//line "<stdout>":842
yy68:
	cursor++
//line "search/normalize.re.go":183
	{ return cursor, Pch, false }
//line "<stdout>":847
yy69:
	cursor++
//line "search/normalize.re.go":195
	{ return cursor, Pdh, false }
//line "<stdout>":852
yy70:
	cursor++
//line "search/normalize.re.go":180
	{ return cursor, Pgh, false }
//line "<stdout>":857
yy71:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xB1:
		goto yy93
	default:
		goto yy72
	}
yy72:
	cursor = marker
	switch (yyaccept) {
	case 0:
		goto yy25
	case 1:
		goto yy32
	case 2:
		goto yy34
	case 3:
		goto yy40
	case 4:
		goto yy49
	case 5:
		goto yy86
	case 6:
		goto yy95
	default:
		goto yy98
	}
yy73:
	cursor++
//line "search/normalize.re.go":185
	{ return cursor, Pjh, false }
//line "<stdout>":891
yy74:
	cursor++
//line "search/normalize.re.go":178
	{ return cursor, Pkh, false }
//line "<stdout>":896
yy75:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA5:
		goto yy94
	default:
		goto yy72
	}
yy76:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x83:
		fallthrough
	case 0x90:
		goto yy96
	default:
		goto yy72
	}
yy77:
	cursor++
//line "search/normalize.re.go":198
	{ return cursor, Pph, false }
//line "<stdout>":921
yy78:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA5:
		goto yy97
	default:
		goto yy72
	}
yy79:
	cursor++
//line "search/normalize.re.go":193
	{ return cursor, Pth, false }
//line "<stdout>":935
yy80:
	cursor++
//line "search/normalize.re.go":186
	{ return cursor, Pñ, false }
//line "<stdout>":940
yy81:
	cursor++
//line "search/normalize.re.go":160
	{ return cursor, Pā, false }
//line "<stdout>":945
yy82:
	cursor++
//line "search/normalize.re.go":162
	{ return cursor, Pī, false }
//line "<stdout>":950
yy83:
	cursor++
//line "search/normalize.re.go":206
	{ return cursor, Pś, false }
//line "<stdout>":955
yy84:
	cursor++
//line "search/normalize.re.go":164
	{ return cursor, Pū, false }
//line "<stdout>":960
yy85:
	yyaccept = 5
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy99
	default:
		goto yy86
	}
yy86:
//line "search/normalize.re.go":213
	{ return cursor, Pschwa, false }
//line "<stdout>":975
yy87:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	default:
		goto yy72
	}
yy88:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B:
		fallthrough
	case 0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3:
		fallthrough
	case 0xA6,0xA7,0xA8,0xA9:
		fallthrough
	case 0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5:
		fallthrough
	case 0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x8C,0x8D:
		goto yy100
	case 0xA4,0xA5:
		fallthrough
	case 0xAA,0xAB:
		goto yy93
	case 0xB6,0xB7:
		goto yy102
	case 0xB8,0xB9:
		goto yy103
	default:
		goto yy72
	}
yy89:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83:
		goto yy96
	case 0x84,0x85:
		goto yy104
	case 0x86,0x87:
		goto yy105
	case 0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99:
		fallthrough
	case 0x9E,0x9F,0xA0,0xA1:
		fallthrough
	case 0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB:
		fallthrough
	case 0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x9A,0x9B:
		goto yy106
	case 0x9C,0x9D:
		goto yy107
	case 0xA2,0xA3:
		goto yy108
	case 0xAC,0xAD:
		goto yy109
	default:
		goto yy72
	}
yy90:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95:
		fallthrough
	case 0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x96:
		goto yy93
	default:
		goto yy72
	}
yy91:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98:
		fallthrough
	case 0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy1
	case 0x99:
		goto yy2
	default:
		goto yy72
	}
yy92:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy87
	default:
		goto yy72
	}
yy93:
	cursor++
//line "search/normalize.re.go":176
	{ return cursor, Pḥ, false }
//line "<stdout>":1080
yy94:
	yyaccept = 6
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy111
	default:
		goto yy95
	}
yy95:
//line "search/normalize.re.go":167
	{ return cursor, Pḷ, false }
//line "<stdout>":1095
yy96:
	cursor++
//line "search/normalize.re.go":174
	{ return cursor, Pṃ, false }
//line "<stdout>":1100
yy97:
	yyaccept = 7
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy112
	default:
		goto yy98
	}
yy98:
//line "search/normalize.re.go":165
	{ return cursor, Pṛ, false }
//line "<stdout>":1115
yy99:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy113
	default:
		goto yy72
	}
yy100:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy114
	default:
		goto yy101
	}
yy101:
//line "search/normalize.re.go":189
	{ return cursor, Pḍ, false }
//line "<stdout>":1139
yy102:
	cursor++
	goto yy95
yy103:
	cursor++
//line "search/normalize.re.go":168
	{ return cursor, Pḹ, false }
//line "<stdout>":1147
yy104:
	cursor++
//line "search/normalize.re.go":181
	{ return cursor, Pṅ, false }
//line "<stdout>":1152
yy105:
	cursor++
//line "search/normalize.re.go":191
	{ return cursor, Pṇ, false }
//line "<stdout>":1157
yy106:
	cursor++
	goto yy98
yy107:
	cursor++
//line "search/normalize.re.go":166
	{ return cursor, Pṝ, false }
//line "<stdout>":1165
yy108:
	cursor++
//line "search/normalize.re.go":207
	{ return cursor, Pṣ, false }
//line "<stdout>":1170
yy109:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 'H':
		fallthrough
	case 'h':
		goto yy115
	default:
		goto yy110
	}
yy110:
//line "search/normalize.re.go":187
	{ return cursor, Pṭ, false }
//line "<stdout>":1185
yy111:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy103
	default:
		goto yy72
	}
yy112:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy107
	default:
		goto yy72
	}
yy113:
	cursor++
//line "search/normalize.re.go":214
	{ return cursor, Plongschwa, false }
//line "<stdout>":1208
yy114:
	cursor++
//line "search/normalize.re.go":190
	{ return cursor, Pḍh, false }
//line "<stdout>":1213
yy115:
	cursor++
//line "search/normalize.re.go":188
	{ return cursor, Pṭh, false }
//line "<stdout>":1218
}
//line "search/normalize.re.go":232

	return 0, 0, false
}

// consumeToken reads the next token and aligns the cursor with grapheme boundaries.
// It absorbs any trailing combining characters attached to the recognized sequence.
func consumeToken(text string) (int, int, bool) {
	matchLen, rep, elide := lexPrefix(text)
	consumed := 0
	state := -1
	rest := text
	for consumed < matchLen {
		var cluster string
		cluster, rest, _, state = uniseg.StepString(rest, state)
		consumed += len(cluster)
	}
	return consumed, rep, elide
}

// lexReduced applies phonological transformations on the binary representation.
// It maps encoded sequences to a further reduced structural logic.
func lexReduced(encoded string) (int, int) {
	cursor, marker := 0, 0
	_ = cursor
	_ = marker
	_ = encoded
	
//line "<stdout>":1248
{
	var yych byte
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case 0x00:
		goto yy117
	case 0x01,0x02:
		goto yy118
	case 0x03,0x04:
		goto yy119
	case 0x05,0x06:
		goto yy120
	case 0x07,0x08:
		goto yy121
	case '\t','\n':
		goto yy122
	case '\v':
		goto yy123
	case '\f':
		goto yy124
	case '\r':
		goto yy125
	case 0x0E:
		goto yy126
	case 0x0F:
		goto yy127
	case 0x10:
		fallthrough
	case '1':
		goto yy129
	case 0x11:
		goto yy130
	case 0x12:
		fallthrough
	case 0x14:
		goto yy132
	case 0x13:
		goto yy133
	case 0x15:
		goto yy134
	case 0x16:
		goto yy135
	case 0x17:
		fallthrough
	case 0x19:
		goto yy137
	case 0x18:
		goto yy138
	case 0x1A:
		goto yy139
	case 0x1B:
		goto yy140
	case 0x1C:
		fallthrough
	case 0x1E:
		fallthrough
	case '!':
		fallthrough
	case '#':
		goto yy142
	case 0x1D:
		goto yy143
	case 0x1F:
		goto yy144
	case ' ':
		goto yy145
	case '"':
		goto yy146
	case '$':
		goto yy147
	case '%':
		goto yy148
	case '&':
		fallthrough
	case '(':
		goto yy150
	case '\'':
		goto yy151
	case ')':
		goto yy152
	case '*':
		goto yy153
	case '+':
		goto yy155
	case ',':
		goto yy157
	case '-':
		goto yy159
	case '.','/','0':
		goto yy161
	case '2','3':
		goto yy162
	case '>':
		goto yy164
	default:
		goto yy163
	}
yy117:
	cursor++
//line "search/normalize.re.go":267
	{ return 1, Pnul }
//line "<stdout>":1350
yy118:
	cursor++
//line "search/normalize.re.go":333
	{ return cursor, Pa }
//line "<stdout>":1355
yy119:
	cursor++
//line "search/normalize.re.go":334
	{ return cursor, Pi }
//line "<stdout>":1360
yy120:
	cursor++
//line "search/normalize.re.go":335
	{ return cursor, Pu }
//line "<stdout>":1365
yy121:
	cursor++
//line "search/normalize.re.go":336
	{ return cursor, Pṛ }
//line "<stdout>":1370
yy122:
	cursor++
//line "search/normalize.re.go":337
	{ return cursor, Pḷ }
//line "<stdout>":1375
yy123:
	cursor++
//line "search/normalize.re.go":338
	{ return cursor, Pe }
//line "<stdout>":1380
yy124:
	cursor++
//line "search/normalize.re.go":339
	{ return cursor, Pai }
//line "<stdout>":1385
yy125:
	cursor++
//line "search/normalize.re.go":340
	{ return cursor, Po }
//line "<stdout>":1390
yy126:
	cursor++
//line "search/normalize.re.go":341
	{ return cursor, Pau }
//line "<stdout>":1395
yy127:
	cursor++
yy128:
//line "search/normalize.re.go":344
	{ return cursor, Pn }
//line "<stdout>":1401
yy129:
	cursor++
//line "search/normalize.re.go":342
	{ return cursor, Ph }
//line "<stdout>":1406
yy130:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case 0x11,0x12:
		goto yy132
	default:
		goto yy131
	}
yy131:
//line "search/normalize.re.go":343
	{ return cursor, Pk }
//line "<stdout>":1419
yy132:
	cursor++
	goto yy131
yy133:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case 0x13,0x14:
		goto yy132
	default:
		goto yy131
	}
yy134:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case 0x15:
		goto yy127
	default:
		goto yy128
	}
yy135:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case 0x16,0x17:
		goto yy137
	default:
		goto yy136
	}
yy136:
//line "search/normalize.re.go":345
	{ return cursor, Pc }
//line "<stdout>":1453
yy137:
	cursor++
	goto yy136
yy138:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case 0x18,0x19:
		goto yy137
	default:
		goto yy136
	}
yy139:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case 0x1A:
		goto yy127
	default:
		goto yy128
	}
yy140:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case 0x1B,0x1C:
		goto yy142
	default:
		goto yy141
	}
yy141:
//line "search/normalize.re.go":346
	{ return cursor, Pt }
//line "<stdout>":1487
yy142:
	cursor++
	goto yy141
yy143:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case 0x1D,0x1E:
		goto yy142
	default:
		goto yy141
	}
yy144:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case 0x1F:
		goto yy127
	default:
		goto yy128
	}
yy145:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case ' ','!':
		goto yy142
	default:
		goto yy141
	}
yy146:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case '"','#':
		goto yy142
	default:
		goto yy141
	}
yy147:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case '$':
		goto yy127
	default:
		goto yy128
	}
yy148:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case '%','&':
		goto yy150
	default:
		goto yy149
	}
yy149:
//line "search/normalize.re.go":347
	{ return cursor, Pp }
//line "<stdout>":1548
yy150:
	cursor++
	goto yy149
yy151:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case '\'','(':
		goto yy150
	default:
		goto yy149
	}
yy152:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case ')':
		goto yy127
	default:
		goto yy128
	}
yy153:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case '*':
		goto yy165
	default:
		goto yy154
	}
yy154:
//line "search/normalize.re.go":348
	{ return cursor, Py }
//line "<stdout>":1582
yy155:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case '+':
		goto yy166
	default:
		goto yy156
	}
yy156:
//line "search/normalize.re.go":349
	{ return cursor, Pr }
//line "<stdout>":1595
yy157:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case ',':
		goto yy167
	default:
		goto yy158
	}
yy158:
//line "search/normalize.re.go":350
	{ return cursor, Pl }
//line "<stdout>":1608
yy159:
	cursor++
	yych = peekByte(encoded, cursor)
	switch (yych) {
	case '-':
		goto yy168
	default:
		goto yy160
	}
yy160:
//line "search/normalize.re.go":351
	{ return cursor, Pv }
//line "<stdout>":1621
yy161:
	cursor++
//line "search/normalize.re.go":352
	{ return cursor, Ps }
//line "<stdout>":1626
yy162:
	cursor++
//line "search/normalize.re.go":353
	{ return cursor, Pschwa }
//line "<stdout>":1631
yy163:
	cursor++
//line "search/normalize.re.go":356
	{ return 1, int(encoded[0]) }
//line "<stdout>":1636
yy164:
	cursor++
//line "search/normalize.re.go":354
	{ return cursor, Pother }
//line "<stdout>":1641
yy165:
	cursor++
	goto yy154
yy166:
	cursor++
	goto yy156
yy167:
	cursor++
	goto yy158
yy168:
	cursor++
	goto yy160
}
//line "search/normalize.re.go":357

	return 0, 0
}

// encodeSequence converts UTF-8 text to the internal binary sequence without allocating bounds.
// It is optimized for high-speed evaluation during the filtering phase.
func encodeSequence(text string) string {
	var seq strings.Builder
	for len(text) > 0 {
		consumed, rep, elide := consumeToken(text)
		if elide {
			text = text[consumed:]
			continue
		}
		seq.WriteByte(byte(rep))
		text = text[consumed:]
	}
	return seq.String()
}

// encodeSequenceWithBounds converts text to the internal sequence and returns an interleaved bounds array.
// The array alternates original start and original end indices for each byte.
func encodeSequenceWithBounds(text string) (string, []int) {
	var seq strings.Builder
	var bounds []int
	cursor := 0
	for len(text) > 0 {
		consumed, rep, elide := consumeToken(text)
		if elide {
			cursor += consumed
			text = text[consumed:]
			continue
		}
		endCursor := cursor + consumed
		seq.WriteByte(byte(rep))
		bounds = append(bounds, cursor, endCursor)
		cursor = endCursor
		text = text[consumed:]
	}
	return seq.String(), bounds
}

// reduceSequence converts the encoded sequence to a reduced state without calculating positional bounds.
// It applies phonological neutralizations strictly for content matching.
func reduceSequence(encoded string) string {
	var reduced strings.Builder
	for len(encoded) > 0 {
		consumed, rep := lexReduced(encoded)
		if rep == Pnul {
			break
		}
		reduced.WriteByte(byte(rep))
		encoded = encoded[consumed:]
	}
	return reduced.String()
}

// reduceSequenceWithBounds converts the encoded sequence and maintains sequence bounds.
// It maps the reduced byte sequence back to its boundaries within the original encoded sequence.
func reduceSequenceWithBounds(encoded string) (string, []int) {
	var reduced strings.Builder
	var bounds []int
	cursor := 0
	for len(encoded) > 0 {
		consumed, rep := lexReduced(encoded)
		if rep == Pnul {
			break
		}
		reduced.WriteByte(byte(rep))
		bounds = append(bounds, cursor, cursor+consumed)
		cursor += consumed
		encoded = encoded[consumed:]
	}
	return reduced.String(), bounds
}

const normalFirst = 0xE002
const Slongschwa = string(rune(normalFirst + Plongschwa))

var folder = cases.Fold()

// lexNormalPrefix uses a finite state machine to identify the next sequence for normal mode.
// It returns the byte length of the matched sequence, its replacement string, and an elision flag.
func lexNormalPrefix(text string) (int, string, bool) {
	cursor, marker := 0, 0
	_ = cursor
	_ = marker
	_ = text
	
//line "<stdout>":1745
{
	var yych byte
	yyaccept := 0
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,'\t','\n','\v','\f','\r',0x0E,0x0F,0x10,0x11,0x12,0x13,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x1C,0x1D,0x1E,0x1F,' ','!','"','#','$','%','&','\'','(',')','*','+',',','-','.','/','0','1','2','3','4','5','6','7','8','9',':',';','<','=','>','?','@','A','B','C','D','E','F','G':
		fallthrough
	case 'I','J','K':
		fallthrough
	case 'N','O','P','Q':
		fallthrough
	case 'S','T','U','V','W','X','Y','Z','[','\\',']','^','_','`','a','b','c','d','e','f','g','h','i','j','k':
		fallthrough
	case 'n','o','p','q':
		fallthrough
	case 's','t','u','v','w','x','y','z','{','|','}','~',0x7F:
		goto yy170
	case 'H':
		goto yy172
	case 'L':
		fallthrough
	case 'l':
		goto yy173
	case 'M':
		fallthrough
	case 'm':
		goto yy174
	case 'R':
		fallthrough
	case 'r':
		goto yy175
	case 0xC2:
		fallthrough
	case 0xC7,0xC8:
		fallthrough
	case 0xCA,0xCB,0xCC,0xCD,0xCE,0xCF,0xD0,0xD1,0xD2:
		fallthrough
	case 0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF:
		goto yy178
	case 0xC3:
		goto yy179
	case 0xC4:
		goto yy180
	case 0xC5:
		goto yy181
	case 0xC6:
		goto yy182
	case 0xC9:
		goto yy183
	case 0xD3:
		goto yy184
	case 0xE0:
		goto yy185
	case 0xE1:
		goto yy186
	case 0xE2,0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xEB,0xEC,0xED,0xEE,0xEF:
		goto yy187
	case 0xF0:
		goto yy188
	case 0xF1,0xF2,0xF3:
		goto yy189
	case 0xF4:
		goto yy190
	default:
		goto yy176
	}
yy170:
	cursor++
yy171:
//line "search/normalize.re.go":471
	{
		r, size := utf8.DecodeRuneInString(text)
		return size, folder.String(string(r)), false
	}
//line "<stdout>":1820
yy172:
	yyaccept = 0
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy191
	default:
		goto yy171
	}
yy173:
	yyaccept = 0
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy193
	default:
		goto yy171
	}
yy174:
	yyaccept = 0
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy194
	default:
		goto yy171
	}
yy175:
	yyaccept = 0
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy195
	default:
		goto yy171
	}
yy176:
	cursor++
yy177:
//line "search/normalize.re.go":453
	{ return 1, "", true }
//line "<stdout>":1870
yy178:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy170
	default:
		goto yy177
	}
yy179:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85:
		fallthrough
	case 0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5:
		fallthrough
	case 0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy170
	case 0x86:
		fallthrough
	case 0xA6:
		goto yy196
	default:
		goto yy177
	}
yy180:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81:
		fallthrough
	case 0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F:
		fallthrough
	case 0x92,0x93:
		fallthrough
	case 0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB:
		fallthrough
	case 0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy170
	case 0x82,0x83:
		goto yy197
	case 0x90,0x91:
		goto yy198
	case 0x94,0x95:
		goto yy199
	case 0xAC,0xAD:
		goto yy200
	default:
		goto yy177
	}
yy181:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D:
		fallthrough
	case 0x90,0x91:
		fallthrough
	case 0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB:
		fallthrough
	case 0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy170
	case 0x8E,0x8F:
		goto yy201
	case 0x92,0x93:
		goto yy202
	case 0xAC,0xAD:
		goto yy203
	default:
		goto yy177
	}
yy182:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E:
		fallthrough
	case 0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy170
	case 0x8F:
		goto yy204
	default:
		goto yy177
	}
yy183:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98:
		fallthrough
	case 0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy170
	case 0x99:
		goto yy204
	default:
		goto yy177
	}
yy184:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97:
		fallthrough
	case 0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy170
	case 0x98,0x99:
		goto yy205
	default:
		goto yy177
	}
yy185:
	yyaccept = 1
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy207
	default:
		goto yy177
	}
yy186:
	yyaccept = 1
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7:
		fallthrough
	case 0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy207
	case 0xB8:
		goto yy208
	case 0xB9:
		goto yy209
	case 0xBA:
		goto yy210
	default:
		goto yy177
	}
yy187:
	yyaccept = 1
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy207
	default:
		goto yy177
	}
yy188:
	yyaccept = 1
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy211
	default:
		goto yy177
	}
yy189:
	yyaccept = 1
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy211
	default:
		goto yy177
	}
yy190:
	yyaccept = 1
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F:
		goto yy211
	default:
		goto yy177
	}
yy191:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xB1:
		goto yy212
	default:
		goto yy192
	}
yy192:
	cursor = marker
	switch (yyaccept) {
	case 0:
		goto yy171
	case 1:
		goto yy177
	case 2:
		goto yy206
	case 3:
		goto yy214
	default:
		goto yy217
	}
yy193:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA5:
		goto yy213
	default:
		goto yy192
	}
yy194:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x83:
		fallthrough
	case 0x90:
		goto yy215
	default:
		goto yy192
	}
yy195:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xA5:
		goto yy216
	default:
		goto yy192
	}
yy196:
	cursor++
//line "search/normalize.re.go":459
	{ return cursor, "ae", false }
//line "<stdout>":2112
yy197:
	cursor++
//line "search/normalize.re.go":454
	{ return cursor, "a", false }
//line "<stdout>":2117
yy198:
	cursor++
//line "search/normalize.re.go":461
	{ return cursor, "d", false }
//line "<stdout>":2122
yy199:
	cursor++
//line "search/normalize.re.go":455
	{ return cursor, "e", false }
//line "<stdout>":2127
yy200:
	cursor++
//line "search/normalize.re.go":456
	{ return cursor, "i", false }
//line "<stdout>":2132
yy201:
	cursor++
//line "search/normalize.re.go":457
	{ return cursor, "o", false }
//line "<stdout>":2137
yy202:
	cursor++
//line "search/normalize.re.go":460
	{ return cursor, "oe", false }
//line "<stdout>":2142
yy203:
	cursor++
//line "search/normalize.re.go":458
	{ return cursor, "u", false }
//line "<stdout>":2147
yy204:
	yyaccept = 0
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy218
	default:
		goto yy171
	}
yy205:
	yyaccept = 2
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy218
	default:
		goto yy206
	}
yy206:
//line "search/normalize.re.go":466
	{ return cursor, "ə", false }
//line "<stdout>":2173
yy207:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy170
	default:
		goto yy192
	}
yy208:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3:
		fallthrough
	case 0xA6,0xA7,0xA8,0xA9:
		fallthrough
	case 0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy170
	case 0xA4,0xA5:
		fallthrough
	case 0xAA,0xAB:
		goto yy212
	default:
		goto yy192
	}
yy209:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83:
		goto yy215
	case 0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy170
	default:
		goto yy192
	}
yy210:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95:
		fallthrough
	case 0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy170
	case 0x96:
		goto yy212
	default:
		goto yy192
	}
yy211:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy207
	default:
		goto yy192
	}
yy212:
	cursor++
//line "search/normalize.re.go":469
	{ return cursor, "ḥ", false }
//line "<stdout>":2237
yy213:
	yyaccept = 3
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy219
	default:
		goto yy214
	}
yy214:
//line "search/normalize.re.go":464
	{ return cursor, "ḷ", false }
//line "<stdout>":2252
yy215:
	cursor++
//line "search/normalize.re.go":468
	{ return cursor, "ṃ", false }
//line "<stdout>":2257
yy216:
	yyaccept = 4
	cursor++
	marker = cursor
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0xCC:
		goto yy220
	default:
		goto yy217
	}
yy217:
//line "search/normalize.re.go":462
	{ return cursor, "ṛ", false }
//line "<stdout>":2272
yy218:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy221
	default:
		goto yy192
	}
yy219:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy222
	default:
		goto yy192
	}
yy220:
	cursor++
	yych = peekByte(text, cursor)
	switch (yych) {
	case 0x84:
		goto yy223
	default:
		goto yy192
	}
yy221:
	cursor++
//line "search/normalize.re.go":467
	{ return cursor, Slongschwa, false }
//line "<stdout>":2304
yy222:
	cursor++
//line "search/normalize.re.go":465
	{ return cursor, "ḹ", false }
//line "<stdout>":2309
yy223:
	cursor++
//line "search/normalize.re.go":463
	{ return cursor, "ṹ", false }
//line "<stdout>":2314
}
//line "search/normalize.re.go":475

	return 0, "", false
}

// consumeNormalToken reads the next token and aligns with grapheme boundaries.
// It discards trailing combining characters to keep only the base normalization.
// Note: this logic incorrectly handles Unicode Regional Indicator sequences.
// Because emoji flags are formed by pairs of Regional Indicators within a single
// grapheme cluster, the second indicator is deliberately but erroneously stripped.
func consumeNormalToken(text string) (int, string, bool) {
	matchLen, rep, elide := lexNormalPrefix(text)
	consumed := 0
	state := -1
	rest := text
	for consumed < matchLen {
		var cluster string
		cluster, rest, _, state = uniseg.StepString(rest, state)
		consumed += len(cluster)
	}
	return consumed, rep, elide
}

// transformNormal applies transformations for normal matching without allocating memory bounds.
// This fast path is crucial for eliminating garbage collection overhead during filtering.
func transformNormal(text string) string {
	var folded strings.Builder
	for len(text) > 0 {
		consumed, rep, elide := consumeNormalToken(text)
		if elide {
			text = text[consumed:]
			continue
		}
		folded.WriteString(rep)
		text = text[consumed:]
	}
	return folded.String()
}

// transformNormalWithBounds applies transformations and records interleaved index bounds.
// The returned array stores the exact original start and end byte offsets.
func transformNormalWithBounds(text string) (string, []int) {
	var folded strings.Builder
	var bounds []int
	cursor := 0
	for len(text) > 0 {
		consumed, rep, elide := consumeNormalToken(text)
		if elide {
			cursor += consumed
			text = text[consumed:]
			continue
		}
		endCursor := cursor + consumed
		n := len(rep)
		for j := 0; j < n; j++ {
			bounds = append(bounds, cursor, endCursor)
		}
		folded.WriteString(rep)
		cursor = endCursor
		text = text[consumed:]
	}
	return folded.String(), bounds
}

// transformNormalized executes the complete formb pipeline purely for content evaluation.
// It bypasses the generation of transitive index bounds to conserve memory.
func transformNormalized(text string) string {
	return reduceSequence(encodeSequence(text))
}

// transformNormalizedWithBounds tracks structural limits across the double normalization.
// It recursively retrieves the initial offsets using the boundaries of the reduced sequence.
func transformNormalizedWithBounds(text string) (string, []int) {
	seq, boundsA := encodeSequenceWithBounds(text)
	reduced, boundsB := reduceSequenceWithBounds(seq)
	var finalBounds []int
	for i := 0; i < len(reduced); i++ {
		startA := boundsB[2*i]
		endA := boundsB[2*i+1] - 1
		finalBounds = append(finalBounds, boundsA[2*startA], boundsA[2*endA+1])
	}
	return reduced, finalBounds
}

// transform acts as a fast text dispatcher ignoring positional metadata.
// It is intended for boolean evaluation matrices.
func transform(text string, mode string) string {
	if mode == "formb" {
		return transformNormalized(text)
	}
	return transformNormal(text)
}

// transformWithBounds computes structural offsets alongside textual mapping.
// It is strictly reserved for the final highlight processing layer.
func transformWithBounds(text string, mode string) (string, []int) {
	if mode == "formb" {
		return transformNormalizedWithBounds(text)
	}
	return transformNormalWithBounds(text)
}
